/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * 代金券表
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CouponRecord extends org.jooq.impl.UpdatableRecordImpl<com.breakfast.domain.tables.records.CouponRecord> implements org.jooq.Record7<java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.math.BigDecimal, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 317068391;

	/**
	 * Setter for <code>breakfast.coupon.coupon_id</code>.
	 */
	public void setCouponId(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>breakfast.coupon.coupon_id</code>.
	 */
	public java.lang.String getCouponId() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>breakfast.coupon.user_id</code>. 发放对象ID
	 */
	public void setUserId(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>breakfast.coupon.user_id</code>. 发放对象ID
	 */
	public java.lang.String getUserId() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>breakfast.coupon.create_time</code>. 发放时间
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>breakfast.coupon.create_time</code>. 发放时间
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>breakfast.coupon.end_time</code>. 截止日期
	 */
	public void setEndTime(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>breakfast.coupon.end_time</code>. 截止日期
	 */
	public java.sql.Timestamp getEndTime() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>breakfast.coupon.price</code>. 价值
	 */
	public void setPrice(java.math.BigDecimal value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>breakfast.coupon.price</code>. 价值
	 */
	public java.math.BigDecimal getPrice() {
		return (java.math.BigDecimal) getValue(4);
	}

	/**
	 * Setter for <code>breakfast.coupon.source</code>. 发放人
	 */
	public void setSource(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>breakfast.coupon.source</code>. 发放人
	 */
	public java.lang.String getSource() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>breakfast.coupon.status</code>. 状态
	 */
	public void setStatus(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>breakfast.coupon.status</code>. 状态
	 */
	public java.lang.String getStatus() {
		return (java.lang.String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.math.BigDecimal, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.math.BigDecimal, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.breakfast.domain.tables.Coupon.Coupon.COUPON_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.breakfast.domain.tables.Coupon.Coupon.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field3() {
		return com.breakfast.domain.tables.Coupon.Coupon.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return com.breakfast.domain.tables.Coupon.Coupon.END_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field5() {
		return com.breakfast.domain.tables.Coupon.Coupon.PRICE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.breakfast.domain.tables.Coupon.Coupon.SOURCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.breakfast.domain.tables.Coupon.Coupon.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getCouponId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value3() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getEndTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value5() {
		return getPrice();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getSource();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CouponRecord value1(java.lang.String value) {
		setCouponId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CouponRecord value2(java.lang.String value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CouponRecord value3(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CouponRecord value4(java.sql.Timestamp value) {
		setEndTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CouponRecord value5(java.math.BigDecimal value) {
		setPrice(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CouponRecord value6(java.lang.String value) {
		setSource(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CouponRecord value7(java.lang.String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CouponRecord values(java.lang.String value1, java.lang.String value2, java.sql.Timestamp value3, java.sql.Timestamp value4, java.math.BigDecimal value5, java.lang.String value6, java.lang.String value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CouponRecord
	 */
	public CouponRecord() {
		super(com.breakfast.domain.tables.Coupon.Coupon);
	}

	/**
	 * Create a detached, initialised CouponRecord
	 */
	public CouponRecord(java.lang.String couponId, java.lang.String userId, java.sql.Timestamp createTime, java.sql.Timestamp endTime, java.math.BigDecimal price, java.lang.String source, java.lang.String status) {
		super(com.breakfast.domain.tables.Coupon.Coupon);

		setValue(0, couponId);
		setValue(1, userId);
		setValue(2, createTime);
		setValue(3, endTime);
		setValue(4, price);
		setValue(5, source);
		setValue(6, status);
	}
}
