/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * 套餐表
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SetMealRecord extends org.jooq.impl.UpdatableRecordImpl<com.breakfast.domain.tables.records.SetMealRecord> implements org.jooq.Record12<java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.math.BigDecimal, java.math.BigDecimal, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -426405963;

	/**
	 * Setter for <code>breakfast.t_bf_set_meal.set_meal_id</code>.
	 */
	public void setSetMealId(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_set_meal.set_meal_id</code>.
	 */
	public java.lang.String getSetMealId() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>breakfast.t_bf_set_meal.set_name</code>. 套餐名称
	 */
	public void setSetName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_set_meal.set_name</code>. 套餐名称
	 */
	public java.lang.String getSetName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>breakfast.t_bf_set_meal.introduce</code>. 套餐说明
	 */
	public void setIntroduce(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_set_meal.introduce</code>. 套餐说明
	 */
	public java.lang.String getIntroduce() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>breakfast.t_bf_set_meal.star_time</code>. 套餐开始日期
	 */
	public void setStarTime(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_set_meal.star_time</code>. 套餐开始日期
	 */
	public java.sql.Timestamp getStarTime() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>breakfast.t_bf_set_meal.end_time</code>. 套餐结束日期
	 */
	public void setEndTime(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_set_meal.end_time</code>. 套餐结束日期
	 */
	public java.sql.Timestamp getEndTime() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>breakfast.t_bf_set_meal.price</code>. 套餐价格
	 */
	public void setPrice(java.math.BigDecimal value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_set_meal.price</code>. 套餐价格
	 */
	public java.math.BigDecimal getPrice() {
		return (java.math.BigDecimal) getValue(5);
	}

	/**
	 * Setter for <code>breakfast.t_bf_set_meal.privilege</code>. 套餐优惠
	 */
	public void setPrivilege(java.math.BigDecimal value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_set_meal.privilege</code>. 套餐优惠
	 */
	public java.math.BigDecimal getPrivilege() {
		return (java.math.BigDecimal) getValue(6);
	}

	/**
	 * Setter for <code>breakfast.t_bf_set_meal.status</code>. 状态：上架PUTAWAY、下架SOLD_PUT、废弃DISCARD
	 */
	public void setStatus(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_set_meal.status</code>. 状态：上架PUTAWAY、下架SOLD_PUT、废弃DISCARD
	 */
	public java.lang.String getStatus() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>breakfast.t_bf_set_meal.food_count</code>. 假库存数
	 */
	public void setFoodCount(java.lang.Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_set_meal.food_count</code>. 假库存数
	 */
	public java.lang.Integer getFoodCount() {
		return (java.lang.Integer) getValue(8);
	}

	/**
	 * Setter for <code>breakfast.t_bf_set_meal.real_food_count</code>. 真实库存
	 */
	public void setRealFoodCount(java.lang.Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_set_meal.real_food_count</code>. 真实库存
	 */
	public java.lang.Integer getRealFoodCount() {
		return (java.lang.Integer) getValue(9);
	}

	/**
	 * Setter for <code>breakfast.t_bf_set_meal.small_pic_id</code>. 缩略图
	 */
	public void setSmallPicId(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_set_meal.small_pic_id</code>. 缩略图
	 */
	public java.lang.String getSmallPicId() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>breakfast.t_bf_set_meal.orgin_pic_id</code>. 原图
	 */
	public void setOrginPicId(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_set_meal.orgin_pic_id</code>. 原图
	 */
	public java.lang.String getOrginPicId() {
		return (java.lang.String) getValue(11);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record12 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.math.BigDecimal, java.math.BigDecimal, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row12) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.math.BigDecimal, java.math.BigDecimal, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row12) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.breakfast.domain.tables.SetMeal.SetMeal.setMealId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.breakfast.domain.tables.SetMeal.SetMeal.setName;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.breakfast.domain.tables.SetMeal.SetMeal.introduce;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return com.breakfast.domain.tables.SetMeal.SetMeal.starTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return com.breakfast.domain.tables.SetMeal.SetMeal.endTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field6() {
		return com.breakfast.domain.tables.SetMeal.SetMeal.price;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field7() {
		return com.breakfast.domain.tables.SetMeal.SetMeal.privilege;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.breakfast.domain.tables.SetMeal.SetMeal.status;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field9() {
		return com.breakfast.domain.tables.SetMeal.SetMeal.foodCount;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field10() {
		return com.breakfast.domain.tables.SetMeal.SetMeal.realFoodCount;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return com.breakfast.domain.tables.SetMeal.SetMeal.smallPicId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return com.breakfast.domain.tables.SetMeal.SetMeal.orginPicId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getSetMealId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getSetName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getIntroduce();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getStarTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getEndTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value6() {
		return getPrice();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value7() {
		return getPrivilege();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value9() {
		return getFoodCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value10() {
		return getRealFoodCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getSmallPicId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getOrginPicId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SetMealRecord value1(java.lang.String value) {
		setSetMealId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SetMealRecord value2(java.lang.String value) {
		setSetName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SetMealRecord value3(java.lang.String value) {
		setIntroduce(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SetMealRecord value4(java.sql.Timestamp value) {
		setStarTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SetMealRecord value5(java.sql.Timestamp value) {
		setEndTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SetMealRecord value6(java.math.BigDecimal value) {
		setPrice(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SetMealRecord value7(java.math.BigDecimal value) {
		setPrivilege(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SetMealRecord value8(java.lang.String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SetMealRecord value9(java.lang.Integer value) {
		setFoodCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SetMealRecord value10(java.lang.Integer value) {
		setRealFoodCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SetMealRecord value11(java.lang.String value) {
		setSmallPicId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SetMealRecord value12(java.lang.String value) {
		setOrginPicId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SetMealRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.sql.Timestamp value4, java.sql.Timestamp value5, java.math.BigDecimal value6, java.math.BigDecimal value7, java.lang.String value8, java.lang.Integer value9, java.lang.Integer value10, java.lang.String value11, java.lang.String value12) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SetMealRecord
	 */
	public SetMealRecord() {
		super(com.breakfast.domain.tables.SetMeal.SetMeal);
	}

	/**
	 * Create a detached, initialised SetMealRecord
	 */
	public SetMealRecord(java.lang.String setMealId, java.lang.String setName, java.lang.String introduce, java.sql.Timestamp starTime, java.sql.Timestamp endTime, java.math.BigDecimal price, java.math.BigDecimal privilege, java.lang.String status, java.lang.Integer foodCount, java.lang.Integer realFoodCount, java.lang.String smallPicId, java.lang.String orginPicId) {
		super(com.breakfast.domain.tables.SetMeal.SetMeal);

		setValue(0, setMealId);
		setValue(1, setName);
		setValue(2, introduce);
		setValue(3, starTime);
		setValue(4, endTime);
		setValue(5, price);
		setValue(6, privilege);
		setValue(7, status);
		setValue(8, foodCount);
		setValue(9, realFoodCount);
		setValue(10, smallPicId);
		setValue(11, orginPicId);
	}
}
