/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * 供应商
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBfProviderRecord extends org.jooq.impl.TableRecordImpl<com.breakfast.domain.tables.records.TBfProviderRecord> implements org.jooq.Record7<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1259210642;

	/**
	 * Setter for <code>breakfast.t_bf_provider.provider_id</code>.
	 */
	public void setProviderId(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_provider.provider_id</code>.
	 */
	public java.lang.String getProviderId() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>breakfast.t_bf_provider.provider_name</code>. 供应商名称
	 */
	public void setProviderName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_provider.provider_name</code>. 供应商名称
	 */
	public java.lang.String getProviderName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>breakfast.t_bf_provider.phone</code>. 常用电话
	 */
	public void setPhone(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_provider.phone</code>. 常用电话
	 */
	public java.lang.String getPhone() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>breakfast.t_bf_provider.alternative_phone</code>. 备用电话
	 */
	public void setAlternativePhone(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_provider.alternative_phone</code>. 备用电话
	 */
	public java.lang.String getAlternativePhone() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>breakfast.t_bf_provider.address</code>. 地址
	 */
	public void setAddress(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_provider.address</code>. 地址
	 */
	public java.lang.String getAddress() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>breakfast.t_bf_provider.intro</code>. 描述
	 */
	public void setIntro(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_provider.intro</code>. 描述
	 */
	public java.lang.String getIntro() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>breakfast.t_bf_provider.status</code>. 状态
	 */
	public void setStatus(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_provider.status</code>. 状态
	 */
	public java.lang.String getStatus() {
		return (java.lang.String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.breakfast.domain.tables.TBfProvider.tBfProvider.PROVIDER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.breakfast.domain.tables.TBfProvider.tBfProvider.PROVIDER_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.breakfast.domain.tables.TBfProvider.tBfProvider.PHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.breakfast.domain.tables.TBfProvider.tBfProvider.ALTERNATIVE_PHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.breakfast.domain.tables.TBfProvider.tBfProvider.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.breakfast.domain.tables.TBfProvider.tBfProvider.INTRO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.breakfast.domain.tables.TBfProvider.tBfProvider.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getProviderId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getProviderName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getPhone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getAlternativePhone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getIntro();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBfProviderRecord value1(java.lang.String value) {
		setProviderId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBfProviderRecord value2(java.lang.String value) {
		setProviderName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBfProviderRecord value3(java.lang.String value) {
		setPhone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBfProviderRecord value4(java.lang.String value) {
		setAlternativePhone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBfProviderRecord value5(java.lang.String value) {
		setAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBfProviderRecord value6(java.lang.String value) {
		setIntro(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBfProviderRecord value7(java.lang.String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TBfProviderRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.String value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TBfProviderRecord
	 */
	public TBfProviderRecord() {
		super(com.breakfast.domain.tables.TBfProvider.tBfProvider);
	}

	/**
	 * Create a detached, initialised TBfProviderRecord
	 */
	public TBfProviderRecord(java.lang.String providerId, java.lang.String providerName, java.lang.String phone, java.lang.String alternativePhone, java.lang.String address, java.lang.String intro, java.lang.String status) {
		super(com.breakfast.domain.tables.TBfProvider.tBfProvider);

		setValue(0, providerId);
		setValue(1, providerName);
		setValue(2, phone);
		setValue(3, alternativePhone);
		setValue(4, address);
		setValue(5, intro);
		setValue(6, status);
	}
}
