/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * 代金券表
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TCouponRecord extends org.jooq.impl.UpdatableRecordImpl<TCouponRecord> implements org.jooq.Record15<String, String, org.joda.time.DateTime, org.joda.time.DateTime, java.math.BigDecimal, String, String, String, String, org.joda.time.DateTime, String, org.joda.time.DateTime, String, Long, String> {

	private static final long serialVersionUID = -1730004212;

	/**
	 * Setter for <code>breakfast.t_bf_coupon.coupon_id</code>.
	 */
	public void setCouponId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_coupon.coupon_id</code>.
	 */
	public String getCouponId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>breakfast.t_bf_coupon.user_id</code>. 发放对象ID
	 */
	public void setUserId(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_coupon.user_id</code>. 发放对象ID
	 */
	public String getUserId() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>breakfast.t_bf_coupon.start_time</code>. 发放时间
	 */
	public void setStartTime(org.joda.time.DateTime value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_coupon.start_time</code>. 发放时间
	 */
	public org.joda.time.DateTime getStartTime() {
		return (org.joda.time.DateTime) getValue(2);
	}

	/**
	 * Setter for <code>breakfast.t_bf_coupon.end_time</code>. 截止日期
	 */
	public void setEndTime(org.joda.time.DateTime value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_coupon.end_time</code>. 截止日期
	 */
	public org.joda.time.DateTime getEndTime() {
		return (org.joda.time.DateTime) getValue(3);
	}

	/**
	 * Setter for <code>breakfast.t_bf_coupon.price</code>. 价值
	 */
	public void setPrice(java.math.BigDecimal value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_coupon.price</code>. 价值
	 */
	public java.math.BigDecimal getPrice() {
		return (java.math.BigDecimal) getValue(4);
	}

	/**
	 * Setter for <code>breakfast.t_bf_coupon.source</code>. 发放人
	 */
	public void setSource(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_coupon.source</code>. 发放人
	 */
	public String getSource() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>breakfast.t_bf_coupon.status</code>. 状态
	 */
	public void setStatus(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_coupon.status</code>. 状态
	 */
	public String getStatus() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>breakfast.t_bf_coupon.brief_intro</code>. 简介
	 */
	public void setBriefIntro(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_coupon.brief_intro</code>. 简介
	 */
	public String getBriefIntro() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>breakfast.t_bf_coupon.send_coupon_id</code>.
	 */
	public void setSendCouponId(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_coupon.send_coupon_id</code>.
	 */
	public String getSendCouponId() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>breakfast.t_bf_coupon.create_time</code>. 创建时间
	 */
	public void setCreateTime(org.joda.time.DateTime value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_coupon.create_time</code>. 创建时间
	 */
	public org.joda.time.DateTime getCreateTime() {
		return (org.joda.time.DateTime) getValue(9);
	}

	/**
	 * Setter for <code>breakfast.t_bf_coupon.create_by</code>. 创建人
	 */
	public void setCreateBy(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_coupon.create_by</code>. 创建人
	 */
	public String getCreateBy() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>breakfast.t_bf_coupon.last_modify_time</code>. 最后修改时间
	 */
	public void setLastModifyTime(org.joda.time.DateTime value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_coupon.last_modify_time</code>. 最后修改时间
	 */
	public org.joda.time.DateTime getLastModifyTime() {
		return (org.joda.time.DateTime) getValue(11);
	}

	/**
	 * Setter for <code>breakfast.t_bf_coupon.last_modify_by</code>. 最后修改人
	 */
	public void setLastModifyBy(String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_coupon.last_modify_by</code>. 最后修改人
	 */
	public String getLastModifyBy() {
		return (String) getValue(12);
	}

	/**
	 * Setter for <code>breakfast.t_bf_coupon.opt_time</code>. 操作时间
	 */
	public void setOptTime(Long value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_coupon.opt_time</code>. 操作时间
	 */
	public Long getOptTime() {
		return (Long) getValue(13);
	}

	/**
	 * Setter for <code>breakfast.t_bf_coupon.small_pic_id</code>. 缩略图
	 */
	public void setSmallPicId(String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_coupon.small_pic_id</code>. 缩略图
	 */
	public String getSmallPicId() {
		return (String) getValue(14);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record15 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row15<String, String, org.joda.time.DateTime, org.joda.time.DateTime, java.math.BigDecimal, String, String, String, String, org.joda.time.DateTime, String, org.joda.time.DateTime, String, Long, String> fieldsRow() {
		return (org.jooq.Row15) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row15<String, String, org.joda.time.DateTime, org.joda.time.DateTime, java.math.BigDecimal, String, String, String, String, org.joda.time.DateTime, String, org.joda.time.DateTime, String, Long, String> valuesRow() {
		return (org.jooq.Row15) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field1() {
		return com.breakfast.domain.tables.TCoupon.Coupon.couponId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field2() {
		return com.breakfast.domain.tables.TCoupon.Coupon.userId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field3() {
		return com.breakfast.domain.tables.TCoupon.Coupon.startTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field4() {
		return com.breakfast.domain.tables.TCoupon.Coupon.endTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field5() {
		return com.breakfast.domain.tables.TCoupon.Coupon.price;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field6() {
		return com.breakfast.domain.tables.TCoupon.Coupon.source;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field7() {
		return com.breakfast.domain.tables.TCoupon.Coupon.status;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field8() {
		return com.breakfast.domain.tables.TCoupon.Coupon.briefIntro;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field9() {
		return com.breakfast.domain.tables.TCoupon.Coupon.sendCouponId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field10() {
		return com.breakfast.domain.tables.TCoupon.Coupon.createTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field11() {
		return com.breakfast.domain.tables.TCoupon.Coupon.createBy;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field12() {
		return com.breakfast.domain.tables.TCoupon.Coupon.lastModifyTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field13() {
		return com.breakfast.domain.tables.TCoupon.Coupon.lastModifyBy;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Long> field14() {
		return com.breakfast.domain.tables.TCoupon.Coupon.optTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field15() {
		return com.breakfast.domain.tables.TCoupon.Coupon.smallPicId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getCouponId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value3() {
		return getStartTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value4() {
		return getEndTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value5() {
		return getPrice();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getSource();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getBriefIntro();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getSendCouponId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value10() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value11() {
		return getCreateBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value12() {
		return getLastModifyTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value13() {
		return getLastModifyBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value14() {
		return getOptTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value15() {
		return getSmallPicId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TCouponRecord value1(String value) {
		setCouponId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TCouponRecord value2(String value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TCouponRecord value3(org.joda.time.DateTime value) {
		setStartTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TCouponRecord value4(org.joda.time.DateTime value) {
		setEndTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TCouponRecord value5(java.math.BigDecimal value) {
		setPrice(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TCouponRecord value6(String value) {
		setSource(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TCouponRecord value7(String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TCouponRecord value8(String value) {
		setBriefIntro(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TCouponRecord value9(String value) {
		setSendCouponId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TCouponRecord value10(org.joda.time.DateTime value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TCouponRecord value11(String value) {
		setCreateBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TCouponRecord value12(org.joda.time.DateTime value) {
		setLastModifyTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TCouponRecord value13(String value) {
		setLastModifyBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TCouponRecord value14(Long value) {
		setOptTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TCouponRecord value15(String value) {
		setSmallPicId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TCouponRecord values(String value1, String value2, org.joda.time.DateTime value3, org.joda.time.DateTime value4, java.math.BigDecimal value5, String value6, String value7, String value8, String value9, org.joda.time.DateTime value10, String value11, org.joda.time.DateTime value12, String value13, Long value14, String value15) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TCouponRecord
	 */
	public TCouponRecord() {
		super(com.breakfast.domain.tables.TCoupon.Coupon);
	}

	/**
	 * Create a detached, initialised TCouponRecord
	 */
	public TCouponRecord(String couponId, String userId, org.joda.time.DateTime startTime, org.joda.time.DateTime endTime, java.math.BigDecimal price, String source, String status, String briefIntro, String sendCouponId, org.joda.time.DateTime createTime, String createBy, org.joda.time.DateTime lastModifyTime, String lastModifyBy, Long optTime, String smallPicId) {
		super(com.breakfast.domain.tables.TCoupon.Coupon);

		setValue(0, couponId);
		setValue(1, userId);
		setValue(2, startTime);
		setValue(3, endTime);
		setValue(4, price);
		setValue(5, source);
		setValue(6, status);
		setValue(7, briefIntro);
		setValue(8, sendCouponId);
		setValue(9, createTime);
		setValue(10, createBy);
		setValue(11, lastModifyTime);
		setValue(12, lastModifyBy);
		setValue(13, optTime);
		setValue(14, smallPicId);
	}
}
