/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * 元素定义表
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TElementRecord extends org.jooq.impl.UpdatableRecordImpl<TElementRecord> implements org.jooq.Record3<String, String, String> {

	private static final long serialVersionUID = -1933126137;

	/**
	 * Setter for <code>breakfast.t_bf_element.element_id</code>.
	 */
	public void setElementId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_element.element_id</code>.
	 */
	public String getElementId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>breakfast.t_bf_element.element_name</code>. 元素名称
	 */
	public void setElementName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_element.element_name</code>. 元素名称
	 */
	public String getElementName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>breakfast.t_bf_element.unit</code>. 元素计量单位
	 */
	public void setUnit(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_element.unit</code>. 元素计量单位
	 */
	public String getUnit() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<String, String, String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<String, String, String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field1() {
		return com.breakfast.domain.tables.TElement.Element.elementId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field2() {
		return com.breakfast.domain.tables.TElement.Element.elementName;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field3() {
		return com.breakfast.domain.tables.TElement.Element.unit;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getElementId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getElementName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getUnit();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TElementRecord value1(String value) {
		setElementId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TElementRecord value2(String value) {
		setElementName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TElementRecord value3(String value) {
		setUnit(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TElementRecord values(String value1, String value2, String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TElementRecord
	 */
	public TElementRecord() {
		super(com.breakfast.domain.tables.TElement.Element);
	}

	/**
	 * Create a detached, initialised TElementRecord
	 */
	public TElementRecord(String elementId, String elementName, String unit) {
		super(com.breakfast.domain.tables.TElement.Element);

		setValue(0, elementId);
		setValue(1, elementName);
		setValue(2, unit);
	}
}
