/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * 评分详情表
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TGradeRecord extends org.jooq.impl.UpdatableRecordImpl<com.breakfast.domain.tables.records.TGradeRecord> implements org.jooq.Record11<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, org.joda.time.DateTime, java.lang.String, org.joda.time.DateTime, java.lang.String, java.lang.Long> {

	private static final long serialVersionUID = 304057603;

	/**
	 * Setter for <code>breakfast.t_bf_grade.grade_id</code>.
	 */
	public void setGradeId(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_grade.grade_id</code>.
	 */
	public java.lang.String getGradeId() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>breakfast.t_bf_grade.user_id</code>. 评分人
	 */
	public void setUserId(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_grade.user_id</code>. 评分人
	 */
	public java.lang.String getUserId() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>breakfast.t_bf_grade.target_type</code>. 评分对象类别
	 */
	public void setTargetType(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_grade.target_type</code>. 评分对象类别
	 */
	public java.lang.String getTargetType() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>breakfast.t_bf_grade.target_id</code>. 评分对象ID
	 */
	public void setTargetId(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_grade.target_id</code>. 评分对象ID
	 */
	public java.lang.String getTargetId() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>breakfast.t_bf_grade.grade</code>. 评分
	 */
	public void setGrade(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_grade.grade</code>. 评分
	 */
	public java.lang.Integer getGrade() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>breakfast.t_bf_grade.status</code>. 状态
	 */
	public void setStatus(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_grade.status</code>. 状态
	 */
	public java.lang.String getStatus() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>breakfast.t_bf_grade.create_time</code>. 创建时间
	 */
	public void setCreateTime(org.joda.time.DateTime value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_grade.create_time</code>. 创建时间
	 */
	public org.joda.time.DateTime getCreateTime() {
		return (org.joda.time.DateTime) getValue(6);
	}

	/**
	 * Setter for <code>breakfast.t_bf_grade.create_by</code>. 创建人
	 */
	public void setCreateBy(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_grade.create_by</code>. 创建人
	 */
	public java.lang.String getCreateBy() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>breakfast.t_bf_grade.last_modify_time</code>. 最后修改时间
	 */
	public void setLastModifyTime(org.joda.time.DateTime value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_grade.last_modify_time</code>. 最后修改时间
	 */
	public org.joda.time.DateTime getLastModifyTime() {
		return (org.joda.time.DateTime) getValue(8);
	}

	/**
	 * Setter for <code>breakfast.t_bf_grade.last_modify_by</code>. 最后修改人
	 */
	public void setLastModifyBy(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_grade.last_modify_by</code>. 最后修改人
	 */
	public java.lang.String getLastModifyBy() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>breakfast.t_bf_grade.opt_time</code>. 操作时间
	 */
	public void setOptTime(java.lang.Long value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_grade.opt_time</code>. 操作时间
	 */
	public java.lang.Long getOptTime() {
		return (java.lang.Long) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, org.joda.time.DateTime, java.lang.String, org.joda.time.DateTime, java.lang.String, java.lang.Long> fieldsRow() {
		return (org.jooq.Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, org.joda.time.DateTime, java.lang.String, org.joda.time.DateTime, java.lang.String, java.lang.Long> valuesRow() {
		return (org.jooq.Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.breakfast.domain.tables.TGrade.Grade.gradeId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.breakfast.domain.tables.TGrade.Grade.userId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.breakfast.domain.tables.TGrade.Grade.targetType;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.breakfast.domain.tables.TGrade.Grade.targetId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return com.breakfast.domain.tables.TGrade.Grade.grade;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.breakfast.domain.tables.TGrade.Grade.status;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field7() {
		return com.breakfast.domain.tables.TGrade.Grade.createTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.breakfast.domain.tables.TGrade.Grade.createBy;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field9() {
		return com.breakfast.domain.tables.TGrade.Grade.lastModifyTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return com.breakfast.domain.tables.TGrade.Grade.lastModifyBy;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field11() {
		return com.breakfast.domain.tables.TGrade.Grade.optTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getGradeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getTargetType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getTargetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getGrade();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value7() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getCreateBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value9() {
		return getLastModifyTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getLastModifyBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value11() {
		return getOptTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TGradeRecord value1(java.lang.String value) {
		setGradeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TGradeRecord value2(java.lang.String value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TGradeRecord value3(java.lang.String value) {
		setTargetType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TGradeRecord value4(java.lang.String value) {
		setTargetId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TGradeRecord value5(java.lang.Integer value) {
		setGrade(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TGradeRecord value6(java.lang.String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TGradeRecord value7(org.joda.time.DateTime value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TGradeRecord value8(java.lang.String value) {
		setCreateBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TGradeRecord value9(org.joda.time.DateTime value) {
		setLastModifyTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TGradeRecord value10(java.lang.String value) {
		setLastModifyBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TGradeRecord value11(java.lang.Long value) {
		setOptTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TGradeRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.Integer value5, java.lang.String value6, org.joda.time.DateTime value7, java.lang.String value8, org.joda.time.DateTime value9, java.lang.String value10, java.lang.Long value11) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TGradeRecord
	 */
	public TGradeRecord() {
		super(com.breakfast.domain.tables.TGrade.Grade);
	}

	/**
	 * Create a detached, initialised TGradeRecord
	 */
	public TGradeRecord(java.lang.String gradeId, java.lang.String userId, java.lang.String targetType, java.lang.String targetId, java.lang.Integer grade, java.lang.String status, org.joda.time.DateTime createTime, java.lang.String createBy, org.joda.time.DateTime lastModifyTime, java.lang.String lastModifyBy, java.lang.Long optTime) {
		super(com.breakfast.domain.tables.TGrade.Grade);

		setValue(0, gradeId);
		setValue(1, userId);
		setValue(2, targetType);
		setValue(3, targetId);
		setValue(4, grade);
		setValue(5, status);
		setValue(6, createTime);
		setValue(7, createBy);
		setValue(8, lastModifyTime);
		setValue(9, lastModifyBy);
		setValue(10, optTime);
	}
}
