/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * 公告信息表
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TInformationRecord extends org.jooq.impl.UpdatableRecordImpl<TInformationRecord> implements org.jooq.Record14<String, String, String, String, String, org.joda.time.DateTime, String, String, String, org.joda.time.DateTime, String, org.joda.time.DateTime, String, Long> {

	private static final long serialVersionUID = -393277489;

	/**
	 * Setter for <code>breakfast.t_bf_information.information_id</code>.
	 */
	public void setInformationId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_information.information_id</code>.
	 */
	public String getInformationId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>breakfast.t_bf_information.title</code>. 信息标题
	 */
	public void setTitle(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_information.title</code>. 信息标题
	 */
	public String getTitle() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>breakfast.t_bf_information.brief_intro</code>.
	 */
	public void setBriefIntro(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_information.brief_intro</code>.
	 */
	public String getBriefIntro() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>breakfast.t_bf_information.content</code>. 信息内容
	 */
	public void setContent(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_information.content</code>. 信息内容
	 */
	public String getContent() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>breakfast.t_bf_information.information_type</code>. 信息类型
	 */
	public void setInformationType(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_information.information_type</code>. 信息类型
	 */
	public String getInformationType() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>breakfast.t_bf_information.post_time</code>. 发布日期
	 */
	public void setPostTime(org.joda.time.DateTime value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_information.post_time</code>. 发布日期
	 */
	public org.joda.time.DateTime getPostTime() {
		return (org.joda.time.DateTime) getValue(5);
	}

	/**
	 * Setter for <code>breakfast.t_bf_information.post_by</code>. 发布人
	 */
	public void setPostBy(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_information.post_by</code>. 发布人
	 */
	public String getPostBy() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>breakfast.t_bf_information.status</code>. 状态
	 */
	public void setStatus(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_information.status</code>. 状态
	 */
	public String getStatus() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>breakfast.t_bf_information.small_pic_id</code>. 缩略图
	 */
	public void setSmallPicId(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_information.small_pic_id</code>. 缩略图
	 */
	public String getSmallPicId() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>breakfast.t_bf_information.create_time</code>. 创建时间
	 */
	public void setCreateTime(org.joda.time.DateTime value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_information.create_time</code>. 创建时间
	 */
	public org.joda.time.DateTime getCreateTime() {
		return (org.joda.time.DateTime) getValue(9);
	}

	/**
	 * Setter for <code>breakfast.t_bf_information.create_by</code>. 创建人
	 */
	public void setCreateBy(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_information.create_by</code>. 创建人
	 */
	public String getCreateBy() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>breakfast.t_bf_information.last_modify_time</code>. 最后修改时间
	 */
	public void setLastModifyTime(org.joda.time.DateTime value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_information.last_modify_time</code>. 最后修改时间
	 */
	public org.joda.time.DateTime getLastModifyTime() {
		return (org.joda.time.DateTime) getValue(11);
	}

	/**
	 * Setter for <code>breakfast.t_bf_information.last_modify_by</code>. 最后修改人
	 */
	public void setLastModifyBy(String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_information.last_modify_by</code>. 最后修改人
	 */
	public String getLastModifyBy() {
		return (String) getValue(12);
	}

	/**
	 * Setter for <code>breakfast.t_bf_information.opt_time</code>. 操作时间
	 */
	public void setOptTime(Long value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_information.opt_time</code>. 操作时间
	 */
	public Long getOptTime() {
		return (Long) getValue(13);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record14 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row14<String, String, String, String, String, org.joda.time.DateTime, String, String, String, org.joda.time.DateTime, String, org.joda.time.DateTime, String, Long> fieldsRow() {
		return (org.jooq.Row14) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row14<String, String, String, String, String, org.joda.time.DateTime, String, String, String, org.joda.time.DateTime, String, org.joda.time.DateTime, String, Long> valuesRow() {
		return (org.jooq.Row14) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field1() {
		return com.breakfast.domain.tables.TInformation.Information.informationId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field2() {
		return com.breakfast.domain.tables.TInformation.Information.title;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field3() {
		return com.breakfast.domain.tables.TInformation.Information.briefIntro;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field4() {
		return com.breakfast.domain.tables.TInformation.Information.content;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field5() {
		return com.breakfast.domain.tables.TInformation.Information.informationType;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field6() {
		return com.breakfast.domain.tables.TInformation.Information.postTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field7() {
		return com.breakfast.domain.tables.TInformation.Information.postBy;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field8() {
		return com.breakfast.domain.tables.TInformation.Information.status;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field9() {
		return com.breakfast.domain.tables.TInformation.Information.smallPicId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field10() {
		return com.breakfast.domain.tables.TInformation.Information.createTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field11() {
		return com.breakfast.domain.tables.TInformation.Information.createBy;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field12() {
		return com.breakfast.domain.tables.TInformation.Information.lastModifyTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field13() {
		return com.breakfast.domain.tables.TInformation.Information.lastModifyBy;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Long> field14() {
		return com.breakfast.domain.tables.TInformation.Information.optTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getInformationId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getBriefIntro();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getInformationType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value6() {
		return getPostTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getPostBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getSmallPicId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value10() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value11() {
		return getCreateBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value12() {
		return getLastModifyTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value13() {
		return getLastModifyBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value14() {
		return getOptTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInformationRecord value1(String value) {
		setInformationId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInformationRecord value2(String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInformationRecord value3(String value) {
		setBriefIntro(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInformationRecord value4(String value) {
		setContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInformationRecord value5(String value) {
		setInformationType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInformationRecord value6(org.joda.time.DateTime value) {
		setPostTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInformationRecord value7(String value) {
		setPostBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInformationRecord value8(String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInformationRecord value9(String value) {
		setSmallPicId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInformationRecord value10(org.joda.time.DateTime value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInformationRecord value11(String value) {
		setCreateBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInformationRecord value12(org.joda.time.DateTime value) {
		setLastModifyTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInformationRecord value13(String value) {
		setLastModifyBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInformationRecord value14(Long value) {
		setOptTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TInformationRecord values(String value1, String value2, String value3, String value4, String value5, org.joda.time.DateTime value6, String value7, String value8, String value9, org.joda.time.DateTime value10, String value11, org.joda.time.DateTime value12, String value13, Long value14) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TInformationRecord
	 */
	public TInformationRecord() {
		super(com.breakfast.domain.tables.TInformation.Information);
	}

	/**
	 * Create a detached, initialised TInformationRecord
	 */
	public TInformationRecord(String informationId, String title, String briefIntro, String content, String informationType, org.joda.time.DateTime postTime, String postBy, String status, String smallPicId, org.joda.time.DateTime createTime, String createBy, org.joda.time.DateTime lastModifyTime, String lastModifyBy, Long optTime) {
		super(com.breakfast.domain.tables.TInformation.Information);

		setValue(0, informationId);
		setValue(1, title);
		setValue(2, briefIntro);
		setValue(3, content);
		setValue(4, informationType);
		setValue(5, postTime);
		setValue(6, postBy);
		setValue(7, status);
		setValue(8, smallPicId);
		setValue(9, createTime);
		setValue(10, createBy);
		setValue(11, lastModifyTime);
		setValue(12, lastModifyBy);
		setValue(13, optTime);
	}
}
