/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * 人员表
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserRecord extends org.jooq.impl.UpdatableRecordImpl<com.breakfast.domain.tables.records.TUserRecord> implements org.jooq.Record17<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, org.joda.time.DateTime, java.lang.String, org.joda.time.DateTime, java.lang.String, org.joda.time.DateTime, java.lang.String, java.lang.Long> {

	private static final long serialVersionUID = 1838184961;

	/**
	 * Setter for <code>breakfast.t_bf_user.user_id</code>.
	 */
	public void setUserId(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_user.user_id</code>.
	 */
	public java.lang.String getUserId() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>breakfast.t_bf_user.login_name</code>. 用户名
	 */
	public void setLoginName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_user.login_name</code>. 用户名
	 */
	public java.lang.String getLoginName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>breakfast.t_bf_user.password</code>. 密码
	 */
	public void setPassword(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_user.password</code>. 密码
	 */
	public java.lang.String getPassword() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>breakfast.t_bf_user.status</code>. 状态
	 */
	public void setStatus(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_user.status</code>. 状态
	 */
	public java.lang.String getStatus() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>breakfast.t_bf_user.user_type</code>. 用户类型
	 */
	public void setUserType(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_user.user_type</code>. 用户类型
	 */
	public java.lang.String getUserType() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>breakfast.t_bf_user.user_name</code>. 姓名
	 */
	public void setUserName(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_user.user_name</code>. 姓名
	 */
	public java.lang.String getUserName() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>breakfast.t_bf_user.sex</code>. 性别
	 */
	public void setSex(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_user.sex</code>. 性别
	 */
	public java.lang.String getSex() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>breakfast.t_bf_user.mobile</code>. 手机号
	 */
	public void setMobile(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_user.mobile</code>. 手机号
	 */
	public java.lang.String getMobile() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>breakfast.t_bf_user.weixin</code>. 微信号
	 */
	public void setWeixin(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_user.weixin</code>. 微信号
	 */
	public java.lang.String getWeixin() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>breakfast.t_bf_user.qq</code>.
	 */
	public void setQq(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_user.qq</code>.
	 */
	public java.lang.String getQq() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>breakfast.t_bf_user.register_time</code>. 注册日期
	 */
	public void setRegisterTime(org.joda.time.DateTime value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_user.register_time</code>. 注册日期
	 */
	public org.joda.time.DateTime getRegisterTime() {
		return (org.joda.time.DateTime) getValue(10);
	}

	/**
	 * Setter for <code>breakfast.t_bf_user.register_way</code>. 注册方式
	 */
	public void setRegisterWay(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_user.register_way</code>. 注册方式
	 */
	public java.lang.String getRegisterWay() {
		return (java.lang.String) getValue(11);
	}

	/**
	 * Setter for <code>breakfast.t_bf_user.create_time</code>. 创建时间
	 */
	public void setCreateTime(org.joda.time.DateTime value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_user.create_time</code>. 创建时间
	 */
	public org.joda.time.DateTime getCreateTime() {
		return (org.joda.time.DateTime) getValue(12);
	}

	/**
	 * Setter for <code>breakfast.t_bf_user.create_by</code>. 创建人
	 */
	public void setCreateBy(java.lang.String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_user.create_by</code>. 创建人
	 */
	public java.lang.String getCreateBy() {
		return (java.lang.String) getValue(13);
	}

	/**
	 * Setter for <code>breakfast.t_bf_user.last_modify_time</code>. 最后修改时间
	 */
	public void setLastModifyTime(org.joda.time.DateTime value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_user.last_modify_time</code>. 最后修改时间
	 */
	public org.joda.time.DateTime getLastModifyTime() {
		return (org.joda.time.DateTime) getValue(14);
	}

	/**
	 * Setter for <code>breakfast.t_bf_user.last_modify_by</code>. 最后修改人
	 */
	public void setLastModifyBy(java.lang.String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_user.last_modify_by</code>. 最后修改人
	 */
	public java.lang.String getLastModifyBy() {
		return (java.lang.String) getValue(15);
	}

	/**
	 * Setter for <code>breakfast.t_bf_user.opt_time</code>. 操作时间
	 */
	public void setOptTime(java.lang.Long value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>breakfast.t_bf_user.opt_time</code>. 操作时间
	 */
	public java.lang.Long getOptTime() {
		return (java.lang.Long) getValue(16);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record17 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row17<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, org.joda.time.DateTime, java.lang.String, org.joda.time.DateTime, java.lang.String, org.joda.time.DateTime, java.lang.String, java.lang.Long> fieldsRow() {
		return (org.jooq.Row17) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row17<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, org.joda.time.DateTime, java.lang.String, org.joda.time.DateTime, java.lang.String, org.joda.time.DateTime, java.lang.String, java.lang.Long> valuesRow() {
		return (org.jooq.Row17) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.breakfast.domain.tables.TUser.User.userId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.breakfast.domain.tables.TUser.User.loginName;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.breakfast.domain.tables.TUser.User.password;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.breakfast.domain.tables.TUser.User.status;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.breakfast.domain.tables.TUser.User.userType;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.breakfast.domain.tables.TUser.User.userName;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.breakfast.domain.tables.TUser.User.sex;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.breakfast.domain.tables.TUser.User.mobile;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return com.breakfast.domain.tables.TUser.User.weixin;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return com.breakfast.domain.tables.TUser.User.qq;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field11() {
		return com.breakfast.domain.tables.TUser.User.registerTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return com.breakfast.domain.tables.TUser.User.registerWay;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field13() {
		return com.breakfast.domain.tables.TUser.User.createTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field14() {
		return com.breakfast.domain.tables.TUser.User.createBy;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.joda.time.DateTime> field15() {
		return com.breakfast.domain.tables.TUser.User.lastModifyTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field16() {
		return com.breakfast.domain.tables.TUser.User.lastModifyBy;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field17() {
		return com.breakfast.domain.tables.TUser.User.optTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getLoginName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getUserType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getUserName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getSex();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getMobile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getWeixin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getQq();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value11() {
		return getRegisterTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getRegisterWay();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value13() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value14() {
		return getCreateBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.joda.time.DateTime value15() {
		return getLastModifyTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value16() {
		return getLastModifyBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value17() {
		return getOptTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value1(java.lang.String value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value2(java.lang.String value) {
		setLoginName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value3(java.lang.String value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value4(java.lang.String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value5(java.lang.String value) {
		setUserType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value6(java.lang.String value) {
		setUserName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value7(java.lang.String value) {
		setSex(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value8(java.lang.String value) {
		setMobile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value9(java.lang.String value) {
		setWeixin(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value10(java.lang.String value) {
		setQq(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value11(org.joda.time.DateTime value) {
		setRegisterTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value12(java.lang.String value) {
		setRegisterWay(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value13(org.joda.time.DateTime value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value14(java.lang.String value) {
		setCreateBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value15(org.joda.time.DateTime value) {
		setLastModifyTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value16(java.lang.String value) {
		setLastModifyBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value17(java.lang.Long value) {
		setOptTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.String value7, java.lang.String value8, java.lang.String value9, java.lang.String value10, org.joda.time.DateTime value11, java.lang.String value12, org.joda.time.DateTime value13, java.lang.String value14, org.joda.time.DateTime value15, java.lang.String value16, java.lang.Long value17) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TUserRecord
	 */
	public TUserRecord() {
		super(com.breakfast.domain.tables.TUser.User);
	}

	/**
	 * Create a detached, initialised TUserRecord
	 */
	public TUserRecord(java.lang.String userId, java.lang.String loginName, java.lang.String password, java.lang.String status, java.lang.String userType, java.lang.String userName, java.lang.String sex, java.lang.String mobile, java.lang.String weixin, java.lang.String qq, org.joda.time.DateTime registerTime, java.lang.String registerWay, org.joda.time.DateTime createTime, java.lang.String createBy, org.joda.time.DateTime lastModifyTime, java.lang.String lastModifyBy, java.lang.Long optTime) {
		super(com.breakfast.domain.tables.TUser.User);

		setValue(0, userId);
		setValue(1, loginName);
		setValue(2, password);
		setValue(3, status);
		setValue(4, userType);
		setValue(5, userName);
		setValue(6, sex);
		setValue(7, mobile);
		setValue(8, weixin);
		setValue(9, qq);
		setValue(10, registerTime);
		setValue(11, registerWay);
		setValue(12, createTime);
		setValue(13, createBy);
		setValue(14, lastModifyTime);
		setValue(15, lastModifyBy);
		setValue(16, optTime);
	}
}
