/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * 人员表
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends org.jooq.impl.UpdatableRecordImpl<com.breakfast.domain.tables.records.UserRecord> implements org.jooq.Record10<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String> {

	private static final long serialVersionUID = 1914373193;

	/**
	 * Setter for <code>breakfast.user.user_id</code>.
	 */
	public void setUserId(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>breakfast.user.user_id</code>.
	 */
	public java.lang.String getUserId() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>breakfast.user.login_name</code>. 用户名
	 */
	public void setLoginName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>breakfast.user.login_name</code>. 用户名
	 */
	public java.lang.String getLoginName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>breakfast.user.password</code>. 密码
	 */
	public void setPassword(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>breakfast.user.password</code>. 密码
	 */
	public java.lang.String getPassword() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>breakfast.user.status</code>. 状态
	 */
	public void setStatus(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>breakfast.user.status</code>. 状态
	 */
	public java.lang.String getStatus() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>breakfast.user.user_name</code>. 姓名
	 */
	public void setUserName(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>breakfast.user.user_name</code>. 姓名
	 */
	public java.lang.String getUserName() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>breakfast.user.mobile</code>. 手机号
	 */
	public void setMobile(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>breakfast.user.mobile</code>. 手机号
	 */
	public java.lang.String getMobile() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>breakfast.user.weixin</code>. 微信号
	 */
	public void setWeixin(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>breakfast.user.weixin</code>. 微信号
	 */
	public java.lang.String getWeixin() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>breakfast.user.qq</code>.
	 */
	public void setQq(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>breakfast.user.qq</code>.
	 */
	public java.lang.String getQq() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>breakfast.user.create_time</code>. 注册日期
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>breakfast.user.create_time</code>. 注册日期
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>breakfast.user.create_way</code>. 注册方式
	 */
	public void setCreateWay(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>breakfast.user.create_way</code>. 注册方式
	 */
	public java.lang.String getCreateWay() {
		return (java.lang.String) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String> fieldsRow() {
		return (org.jooq.Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String> valuesRow() {
		return (org.jooq.Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.breakfast.domain.tables.User.User.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.breakfast.domain.tables.User.User.LOGIN_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.breakfast.domain.tables.User.User.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.breakfast.domain.tables.User.User.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.breakfast.domain.tables.User.User.USER_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.breakfast.domain.tables.User.User.MOBILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.breakfast.domain.tables.User.User.WEIXIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.breakfast.domain.tables.User.User.QQ;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field9() {
		return com.breakfast.domain.tables.User.User.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return com.breakfast.domain.tables.User.User.CREATE_WAY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getLoginName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getUserName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getMobile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getWeixin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getQq();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value9() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getCreateWay();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value1(java.lang.String value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value2(java.lang.String value) {
		setLoginName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value3(java.lang.String value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value4(java.lang.String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value5(java.lang.String value) {
		setUserName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value6(java.lang.String value) {
		setMobile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value7(java.lang.String value) {
		setWeixin(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value8(java.lang.String value) {
		setQq(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value9(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value10(java.lang.String value) {
		setCreateWay(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.String value7, java.lang.String value8, java.sql.Timestamp value9, java.lang.String value10) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserRecord
	 */
	public UserRecord() {
		super(com.breakfast.domain.tables.User.User);
	}

	/**
	 * Create a detached, initialised UserRecord
	 */
	public UserRecord(java.lang.String userId, java.lang.String loginName, java.lang.String password, java.lang.String status, java.lang.String userName, java.lang.String mobile, java.lang.String weixin, java.lang.String qq, java.sql.Timestamp createTime, java.lang.String createWay) {
		super(com.breakfast.domain.tables.User.User);

		setValue(0, userId);
		setValue(1, loginName);
		setValue(2, password);
		setValue(3, status);
		setValue(4, userName);
		setValue(5, mobile);
		setValue(6, weixin);
		setValue(7, qq);
		setValue(8, createTime);
		setValue(9, createWay);
	}
}
