/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables.pojos;

/**
 * This class is generated by jOOQ.
 *
 * 评价反馈表
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Feedback implements java.io.Serializable {

	private static final long serialVersionUID = -658811895;

	private java.lang.String   feedbackId;
	private java.lang.String   userId;
	private java.lang.String   targetType;
	private java.lang.String   objectId;
	private java.lang.String   content;
	private java.sql.Timestamp createTime;
	private java.sql.Timestamp lastModifyTime;
	private java.lang.String   状态;

	public Feedback() {}

	public Feedback(
		java.lang.String   feedbackId,
		java.lang.String   userId,
		java.lang.String   targetType,
		java.lang.String   objectId,
		java.lang.String   content,
		java.sql.Timestamp createTime,
		java.sql.Timestamp lastModifyTime,
		java.lang.String   状态
	) {
		this.feedbackId = feedbackId;
		this.userId = userId;
		this.targetType = targetType;
		this.objectId = objectId;
		this.content = content;
		this.createTime = createTime;
		this.lastModifyTime = lastModifyTime;
		this.状态 = 状态;
	}

	public java.lang.String getFeedbackId() {
		return this.feedbackId;
	}

	public void setFeedbackId(java.lang.String feedbackId) {
		this.feedbackId = feedbackId;
	}

	public java.lang.String getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.String userId) {
		this.userId = userId;
	}

	public java.lang.String getTargetType() {
		return this.targetType;
	}

	public void setTargetType(java.lang.String targetType) {
		this.targetType = targetType;
	}

	public java.lang.String getObjectId() {
		return this.objectId;
	}

	public void setObjectId(java.lang.String objectId) {
		this.objectId = objectId;
	}

	public java.lang.String getContent() {
		return this.content;
	}

	public void setContent(java.lang.String content) {
		this.content = content;
	}

	public java.sql.Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(java.sql.Timestamp createTime) {
		this.createTime = createTime;
	}

	public java.sql.Timestamp getLastModifyTime() {
		return this.lastModifyTime;
	}

	public void setLastModifyTime(java.sql.Timestamp lastModifyTime) {
		this.lastModifyTime = lastModifyTime;
	}

	public java.lang.String get状态() {
		return this.状态;
	}

	public void set状态(java.lang.String 状态) {
		this.状态 = 状态;
	}
}
