/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables.pojos;

/**
 * This class is generated by jOOQ.
 *
 * 文件表
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class File implements java.io.Serializable {

	private static final long serialVersionUID = 930523501;

	private java.lang.String   fileId;
	private java.lang.String   filePath;
	private java.lang.String   status;
	private java.sql.Timestamp createTime;
	private java.lang.String   createBy;

	public File() {}

	public File(
		java.lang.String   fileId,
		java.lang.String   filePath,
		java.lang.String   status,
		java.sql.Timestamp createTime,
		java.lang.String   createBy
	) {
		this.fileId = fileId;
		this.filePath = filePath;
		this.status = status;
		this.createTime = createTime;
		this.createBy = createBy;
	}

	public java.lang.String getFileId() {
		return this.fileId;
	}

	public void setFileId(java.lang.String fileId) {
		this.fileId = fileId;
	}

	public java.lang.String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(java.lang.String filePath) {
		this.filePath = filePath;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.sql.Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(java.sql.Timestamp createTime) {
		this.createTime = createTime;
	}

	public java.lang.String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(java.lang.String createBy) {
		this.createBy = createBy;
	}
}
