/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables.pojos;

/**
 * This class is generated by jOOQ.
 *
 * 订单详情表
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderDetail implements java.io.Serializable {

	private static final long serialVersionUID = -776662893;

	private String       detailId;
	private String       orderId;
	private String       foodObjId;
	private Integer      foodObjCount;
	private String       foodObjType;
	private java.math.BigDecimal   foodObjPrice;
	private org.joda.time.DateTime createTime;
	private String       createBy;
	private org.joda.time.DateTime lastModifyTime;
	private String       lastModifyBy;
	private Long         optTime;


	private String foodObjName;

	public OrderDetail() {}

	public OrderDetail(
			String detailId,
			String orderId,
			String foodObjId,
			Integer foodObjCount,
			String foodObjType,
			java.math.BigDecimal foodObjPrice,
			org.joda.time.DateTime createTime,
			String createBy,
			org.joda.time.DateTime lastModifyTime,
			String lastModifyBy,
			Long optTime
	) {
		this.detailId = detailId;
		this.orderId = orderId;
		this.foodObjId = foodObjId;
		this.foodObjCount = foodObjCount;
		this.foodObjType = foodObjType;
		this.foodObjPrice = foodObjPrice;
		this.createTime = createTime;
		this.createBy = createBy;
		this.lastModifyTime = lastModifyTime;
		this.lastModifyBy = lastModifyBy;
		this.optTime = optTime;
	}

	public String getDetailId() {
		return this.detailId;
	}

	public void setDetailId(String detailId) {
		this.detailId = detailId;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public String getFoodObjId() {
		return this.foodObjId;
	}

	public void setFoodObjId(String foodObjId) {
		this.foodObjId = foodObjId;
	}

	public Integer getFoodObjCount() {
		return this.foodObjCount;
	}

	public void setFoodObjCount(Integer foodObjCount) {
		this.foodObjCount = foodObjCount;
	}

	public String getFoodObjType() {
		return this.foodObjType;
	}

	public void setFoodObjType(String foodObjType) {
		this.foodObjType = foodObjType;
	}

	public java.math.BigDecimal getFoodObjPrice() {
		return this.foodObjPrice;
	}

	public void setFoodObjPrice(java.math.BigDecimal foodObjPrice) {
		this.foodObjPrice = foodObjPrice;
	}

	public org.joda.time.DateTime getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(org.joda.time.DateTime createTime) {
		this.createTime = createTime;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public org.joda.time.DateTime getLastModifyTime() {
		return this.lastModifyTime;
	}

	public void setLastModifyTime(org.joda.time.DateTime lastModifyTime) {
		this.lastModifyTime = lastModifyTime;
	}

	public String getLastModifyBy() {
		return this.lastModifyBy;
	}

	public void setLastModifyBy(String lastModifyBy) {
		this.lastModifyBy = lastModifyBy;
	}

	public Long getOptTime() {
		return this.optTime;
	}

	public void setOptTime(Long optTime) {
		this.optTime = optTime;
	}


	public String getFoodObjName() {
		return foodObjName;
	}

	public void setFoodObjName(String foodObjName) {
		this.foodObjName = foodObjName;
	}
}
