/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables.pojos;

/**
 * This class is generated by jOOQ.
 *
 * 订单表
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Order implements java.io.Serializable {

	private static final long serialVersionUID = -45462727;

	private java.lang.String  orderId;
	private java.lang.String  customerId;
	private java.lang.String  type;
	private java.lang.String  status;
	private java.lang.String  consigneeName;
	private java.lang.String  consigneeAddress;
	private java.lang.String  consigneeMobile;
	private java.lang.Integer orderPrice;
	private java.lang.Integer exccreaditCount;

	public Order() {}

	public Order(
		java.lang.String  orderId,
		java.lang.String  customerId,
		java.lang.String  type,
		java.lang.String  status,
		java.lang.String  consigneeName,
		java.lang.String  consigneeAddress,
		java.lang.String  consigneeMobile,
		java.lang.Integer orderPrice,
		java.lang.Integer exccreaditCount
	) {
		this.orderId = orderId;
		this.customerId = customerId;
		this.type = type;
		this.status = status;
		this.consigneeName = consigneeName;
		this.consigneeAddress = consigneeAddress;
		this.consigneeMobile = consigneeMobile;
		this.orderPrice = orderPrice;
		this.exccreaditCount = exccreaditCount;
	}

	public java.lang.String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(java.lang.String orderId) {
		this.orderId = orderId;
	}

	public java.lang.String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(java.lang.String customerId) {
		this.customerId = customerId;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getConsigneeName() {
		return this.consigneeName;
	}

	public void setConsigneeName(java.lang.String consigneeName) {
		this.consigneeName = consigneeName;
	}

	public java.lang.String getConsigneeAddress() {
		return this.consigneeAddress;
	}

	public void setConsigneeAddress(java.lang.String consigneeAddress) {
		this.consigneeAddress = consigneeAddress;
	}

	public java.lang.String getConsigneeMobile() {
		return this.consigneeMobile;
	}

	public void setConsigneeMobile(java.lang.String consigneeMobile) {
		this.consigneeMobile = consigneeMobile;
	}

	public java.lang.Integer getOrderPrice() {
		return this.orderPrice;
	}

	public void setOrderPrice(java.lang.Integer orderPrice) {
		this.orderPrice = orderPrice;
	}

	public java.lang.Integer getExccreaditCount() {
		return this.exccreaditCount;
	}

	public void setExccreaditCount(java.lang.Integer exccreaditCount) {
		this.exccreaditCount = exccreaditCount;
	}
}
