/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables.pojos;

/**
 * This class is generated by jOOQ.
 *
 * 图片展示
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PhotoShow implements java.io.Serializable {

	private static final long serialVersionUID = -1517656345;

	private java.lang.String   photoId;
	private java.lang.String   fileId;
	private java.sql.Timestamp createTime;
	private java.sql.Timestamp validDate;
	private java.lang.String   createby;
	private java.lang.String   status;

	public PhotoShow() {}

	public PhotoShow(
		java.lang.String   photoId,
		java.lang.String   fileId,
		java.sql.Timestamp createTime,
		java.sql.Timestamp validDate,
		java.lang.String   createby,
		java.lang.String   status
	) {
		this.photoId = photoId;
		this.fileId = fileId;
		this.createTime = createTime;
		this.validDate = validDate;
		this.createby = createby;
		this.status = status;
	}

	public java.lang.String getPhotoId() {
		return this.photoId;
	}

	public void setPhotoId(java.lang.String photoId) {
		this.photoId = photoId;
	}

	public java.lang.String getFileId() {
		return this.fileId;
	}

	public void setFileId(java.lang.String fileId) {
		this.fileId = fileId;
	}

	public java.sql.Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(java.sql.Timestamp createTime) {
		this.createTime = createTime;
	}

	public java.sql.Timestamp getValidDate() {
		return this.validDate;
	}

	public void setValidDate(java.sql.Timestamp validDate) {
		this.validDate = validDate;
	}

	public java.lang.String getCreateby() {
		return this.createby;
	}

	public void setCreateby(java.lang.String createby) {
		this.createby = createby;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}
}
