/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables.pojos;

import java.util.Map;

/**
 * This class is generated by jOOQ.
 *
 * 图片展示
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PhotoShow implements java.io.Serializable {

	private static final long serialVersionUID = 1379116633;

	private java.lang.String       photoId;
	private java.lang.String       orginFileId;
	private java.lang.String       smallFileId;
	private org.joda.time.DateTime uploadTime;
	private org.joda.time.DateTime validDate;
	private java.lang.String       createby;
	private java.lang.String       status;
	private org.joda.time.DateTime createTime;
	private java.lang.String       createBy;
	private org.joda.time.DateTime lastModifyTime;
	private java.lang.String       lastModifyBy;
	private java.lang.Long         optTime;
	private Map<String, Object> extMap;

	public PhotoShow() {}

	public PhotoShow(
		java.lang.String       photoId,
		java.lang.String       orginFileId,
		java.lang.String       smallFileId,
		org.joda.time.DateTime uploadTime,
		org.joda.time.DateTime validDate,
		java.lang.String       createby,
		java.lang.String       status,
		org.joda.time.DateTime createTime,
		java.lang.String       createBy,
		org.joda.time.DateTime lastModifyTime,
		java.lang.String       lastModifyBy,
		java.lang.Long         optTime
	) {
		this.photoId = photoId;
		this.orginFileId = orginFileId;
		this.smallFileId = smallFileId;
		this.uploadTime = uploadTime;
		this.validDate = validDate;
		this.createby = createby;
		this.status = status;
		this.createTime = createTime;
		this.createBy = createBy;
		this.lastModifyTime = lastModifyTime;
		this.lastModifyBy = lastModifyBy;
		this.optTime = optTime;
	}

	public java.lang.String getPhotoId() {
		return this.photoId;
	}

	public void setPhotoId(java.lang.String photoId) {
		this.photoId = photoId;
	}

	public java.lang.String getOrginFileId() {
		return this.orginFileId;
	}

	public void setOrginFileId(java.lang.String orginFileId) {
		this.orginFileId = orginFileId;
	}

	public java.lang.String getSmallFileId() {
		return this.smallFileId;
	}

	public void setSmallFileId(java.lang.String smallFileId) {
		this.smallFileId = smallFileId;
	}

	public org.joda.time.DateTime getUploadTime() {
		return this.uploadTime;
	}

	public void setUploadTime(org.joda.time.DateTime uploadTime) {
		this.uploadTime = uploadTime;
	}

	public org.joda.time.DateTime getValidDate() {
		return this.validDate;
	}

	public void setValidDate(org.joda.time.DateTime validDate) {
		this.validDate = validDate;
	}

	public java.lang.String getCreateby() {
		return this.createby;
	}

	public void setCreateby(java.lang.String createby) {
		this.createby = createby;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public org.joda.time.DateTime getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(org.joda.time.DateTime createTime) {
		this.createTime = createTime;
	}

	public java.lang.String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(java.lang.String createBy) {
		this.createBy = createBy;
	}

	public org.joda.time.DateTime getLastModifyTime() {
		return this.lastModifyTime;
	}

	public void setLastModifyTime(org.joda.time.DateTime lastModifyTime) {
		this.lastModifyTime = lastModifyTime;
	}

	public java.lang.String getLastModifyBy() {
		return this.lastModifyBy;
	}

	public void setLastModifyBy(java.lang.String lastModifyBy) {
		this.lastModifyBy = lastModifyBy;
	}

	public java.lang.Long getOptTime() {
		return this.optTime;
	}

	public void setOptTime(java.lang.Long optTime) {
		this.optTime = optTime;
	}

	public void setExtMap(Map<String, Object> extMap) {
		this.extMap = extMap;
	}

	public Map<String, Object> getExtMap() {
		return extMap;
	}
}
