/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables.pojos;

/**
 * This class is generated by jOOQ.
 *
 * 套餐食品
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SetFoods implements java.io.Serializable {

	private static final long serialVersionUID = 1432208228;

	private java.lang.String  setFoodsId;
	private java.lang.String  setMealId;
	private java.lang.String  foodId;
	private java.lang.Integer foodCount;

	public SetFoods() {}

	public SetFoods(
		java.lang.String  setFoodsId,
		java.lang.String  setMealId,
		java.lang.String  foodId,
		java.lang.Integer foodCount
	) {
		this.setFoodsId = setFoodsId;
		this.setMealId = setMealId;
		this.foodId = foodId;
		this.foodCount = foodCount;
	}

	public java.lang.String getSetFoodsId() {
		return this.setFoodsId;
	}

	public void setSetFoodsId(java.lang.String setFoodsId) {
		this.setFoodsId = setFoodsId;
	}

	public java.lang.String getSetMealId() {
		return this.setMealId;
	}

	public void setSetMealId(java.lang.String setMealId) {
		this.setMealId = setMealId;
	}

	public java.lang.String getFoodId() {
		return this.foodId;
	}

	public void setFoodId(java.lang.String foodId) {
		this.foodId = foodId;
	}

	public java.lang.Integer getFoodCount() {
		return this.foodCount;
	}

	public void setFoodCount(java.lang.Integer foodCount) {
		this.foodCount = foodCount;
	}
}
