/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables.pojos;

/**
 * This class is generated by jOOQ.
 *
 * 快递员详情
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserCourier implements java.io.Serializable {

	private static final long serialVersionUID = -1395533410;

	private java.lang.String userId;
	private java.lang.String source;

	public UserCourier() {}

	public UserCourier(
		java.lang.String userId,
		java.lang.String source
	) {
		this.userId = userId;
		this.source = source;
	}

	public java.lang.String getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.String userId) {
		this.userId = userId;
	}

	public java.lang.String getSource() {
		return this.source;
	}

	public void setSource(java.lang.String source) {
		this.source = source;
	}
}
