/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables;

/**
 * This class is generated by jOOQ.
 *
 * 原材料食品中间表
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FoodDetail extends org.jooq.impl.TableImpl<com.breakfast.domain.tables.records.FoodDetailRecord> {

	private static final long serialVersionUID = -942271030;

	/**
	 * The singleton instance of <code>breakfast.t_bf_food_detail</code>
	 */
	public static final com.breakfast.domain.tables.FoodDetail FoodDetail = new com.breakfast.domain.tables.FoodDetail();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.breakfast.domain.tables.records.FoodDetailRecord> getRecordType() {
		return com.breakfast.domain.tables.records.FoodDetailRecord.class;
	}

	/**
	 * The column <code>breakfast.t_bf_food_detail.detail_id</code>.
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.FoodDetailRecord, java.lang.String> detailId = createField("detail_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>breakfast.t_bf_food_detail.food_id</code>. 食品ID
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.FoodDetailRecord, java.lang.String> foodId = createField("food_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "食品ID");

	/**
	 * The column <code>breakfast.t_bf_food_detail.raw_material_id</code>. 原材料ID
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.FoodDetailRecord, java.lang.String> rawMaterialId = createField("raw_material_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "原材料ID");

	/**
	 * The column <code>breakfast.t_bf_food_detail.count</code>. 原材料数量
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.FoodDetailRecord, java.lang.Integer> count = createField("count", org.jooq.impl.SQLDataType.INTEGER, this, "原材料数量");

	/**
	 * Create a <code>breakfast.t_bf_food_detail</code> table reference
	 */
	public FoodDetail() {
		this("t_bf_food_detail", null);
	}

	/**
	 * Create an aliased <code>breakfast.t_bf_food_detail</code> table reference
	 */
	public FoodDetail(java.lang.String alias) {
		this(alias, com.breakfast.domain.tables.FoodDetail.FoodDetail);
	}

	private FoodDetail(java.lang.String alias, org.jooq.Table<com.breakfast.domain.tables.records.FoodDetailRecord> aliased) {
		this(alias, aliased, null);
	}

	private FoodDetail(java.lang.String alias, org.jooq.Table<com.breakfast.domain.tables.records.FoodDetailRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.breakfast.domain.Breakfast.breakfast, aliased, parameters, "原材料食品中间表");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.breakfast.domain.tables.records.FoodDetailRecord> getPrimaryKey() {
		return com.breakfast.domain.Keys.keyTBfFoodDetailPrimary;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.breakfast.domain.tables.records.FoodDetailRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.breakfast.domain.tables.records.FoodDetailRecord>>asList(com.breakfast.domain.Keys.keyTBfFoodDetailPrimary);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.breakfast.domain.tables.FoodDetail as(java.lang.String alias) {
		return new com.breakfast.domain.tables.FoodDetail(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.breakfast.domain.tables.FoodDetail rename(java.lang.String name) {
		return new com.breakfast.domain.tables.FoodDetail(name, null);
	}
}
