/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables;

/**
 * This class is generated by jOOQ.
 *
 * 套餐表
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SetMeal extends org.jooq.impl.TableImpl<com.breakfast.domain.tables.records.SetMealRecord> {

	private static final long serialVersionUID = -813669255;

	/**
	 * The singleton instance of <code>breakfast.set_meal</code>
	 */
	public static final com.breakfast.domain.tables.SetMeal SetMeal = new com.breakfast.domain.tables.SetMeal();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.breakfast.domain.tables.records.SetMealRecord> getRecordType() {
		return com.breakfast.domain.tables.records.SetMealRecord.class;
	}

	/**
	 * The column <code>breakfast.set_meal.set_meal_id</code>.
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.SetMealRecord, java.lang.String> SET_MEAL_ID = createField("set_meal_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>breakfast.set_meal.set_name</code>. 套餐名称
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.SetMealRecord, java.lang.String> SET_NAME = createField("set_name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "套餐名称");

	/**
	 * The column <code>breakfast.set_meal.introduce</code>. 套餐说明
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.SetMealRecord, java.lang.String> INTRODUCE = createField("introduce", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "套餐说明");

	/**
	 * The column <code>breakfast.set_meal.star_time</code>. 套餐开始日期
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.SetMealRecord, java.sql.Timestamp> STAR_TIME = createField("star_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "套餐开始日期");

	/**
	 * The column <code>breakfast.set_meal.end_time</code>. 套餐结束日期
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.SetMealRecord, java.sql.Timestamp> END_TIME = createField("end_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "套餐结束日期");

	/**
	 * The column <code>breakfast.set_meal.price</code>. 套餐价格
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.SetMealRecord, java.math.BigDecimal> PRICE = createField("price", org.jooq.impl.SQLDataType.DECIMAL.precision(7, 3), this, "套餐价格");

	/**
	 * The column <code>breakfast.set_meal.privilege</code>. 套餐优惠
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.SetMealRecord, java.math.BigDecimal> PRIVILEGE = createField("privilege", org.jooq.impl.SQLDataType.DECIMAL.precision(7, 3), this, "套餐优惠");

	/**
	 * The column <code>breakfast.set_meal.status</code>. 状态：上架PUTAWAY、下架SOLD_PUT、废弃DISCARD
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.SetMealRecord, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "状态：上架PUTAWAY、下架SOLD_PUT、废弃DISCARD");

	/**
	 * The column <code>breakfast.set_meal.food_count</code>. 假库存数
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.SetMealRecord, java.lang.Integer> FOOD_COUNT = createField("food_count", org.jooq.impl.SQLDataType.INTEGER, this, "假库存数");

	/**
	 * The column <code>breakfast.set_meal.real_food_count</code>. 真实库存
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.SetMealRecord, java.lang.Integer> REAL_FOOD_COUNT = createField("real_food_count", org.jooq.impl.SQLDataType.INTEGER, this, "真实库存");

	/**
	 * The column <code>breakfast.set_meal.small_pic_id</code>. 缩略图
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.SetMealRecord, java.lang.String> SMALL_PIC_ID = createField("small_pic_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "缩略图");

	/**
	 * The column <code>breakfast.set_meal.orgin_pic_id</code>. 原图
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.SetMealRecord, java.lang.String> ORGIN_PIC_ID = createField("orgin_pic_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "原图");

	/**
	 * Create a <code>breakfast.set_meal</code> table reference
	 */
	public SetMeal() {
		this("set_meal", null);
	}

	/**
	 * Create an aliased <code>breakfast.set_meal</code> table reference
	 */
	public SetMeal(java.lang.String alias) {
		this(alias, com.breakfast.domain.tables.SetMeal.SetMeal);
	}

	private SetMeal(java.lang.String alias, org.jooq.Table<com.breakfast.domain.tables.records.SetMealRecord> aliased) {
		this(alias, aliased, null);
	}

	private SetMeal(java.lang.String alias, org.jooq.Table<com.breakfast.domain.tables.records.SetMealRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.breakfast.domain.Breakfast.BREAKFAST, aliased, parameters, "套餐表");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.breakfast.domain.tables.records.SetMealRecord> getPrimaryKey() {
		return com.breakfast.domain.Keys.KEY_SET_MEAL_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.breakfast.domain.tables.records.SetMealRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.breakfast.domain.tables.records.SetMealRecord>>asList(com.breakfast.domain.Keys.KEY_SET_MEAL_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.breakfast.domain.tables.SetMeal as(java.lang.String alias) {
		return new com.breakfast.domain.tables.SetMeal(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.breakfast.domain.tables.SetMeal rename(java.lang.String name) {
		return new com.breakfast.domain.tables.SetMeal(name, null);
	}
}
