/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables;

/**
 * This class is generated by jOOQ.
 *
 * 地址表
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBfAddress extends org.jooq.impl.TableImpl<com.breakfast.domain.tables.records.TBfAddressRecord> {

	private static final long serialVersionUID = 679866625;

	/**
	 * The singleton instance of <code>breakfast.t_bf_address</code>
	 */
	public static final com.breakfast.domain.tables.TBfAddress tBfAddress = new com.breakfast.domain.tables.TBfAddress();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.breakfast.domain.tables.records.TBfAddressRecord> getRecordType() {
		return com.breakfast.domain.tables.records.TBfAddressRecord.class;
	}

	/**
	 * The column <code>breakfast.t_bf_address.adddress_id</code>.
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfAddressRecord, java.lang.String> ADDDRESS_ID = createField("adddress_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>breakfast.t_bf_address.address_name</code>. 地址名
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfAddressRecord, java.lang.String> ADDRESS_NAME = createField("address_name", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "地址名");

	/**
	 * The column <code>breakfast.t_bf_address.address</code>. 地址详情
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfAddressRecord, java.lang.String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "地址详情");

	/**
	 * The column <code>breakfast.t_bf_address.status</code>. 状态
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfAddressRecord, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "状态");

	/**
	 * Create a <code>breakfast.t_bf_address</code> table reference
	 */
	public TBfAddress() {
		this("t_bf_address", null);
	}

	/**
	 * Create an aliased <code>breakfast.t_bf_address</code> table reference
	 */
	public TBfAddress(java.lang.String alias) {
		this(alias, com.breakfast.domain.tables.TBfAddress.tBfAddress);
	}

	private TBfAddress(java.lang.String alias, org.jooq.Table<com.breakfast.domain.tables.records.TBfAddressRecord> aliased) {
		this(alias, aliased, null);
	}

	private TBfAddress(java.lang.String alias, org.jooq.Table<com.breakfast.domain.tables.records.TBfAddressRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.breakfast.domain.Breakfast.BREAKFAST, aliased, parameters, "地址表");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.breakfast.domain.tables.records.TBfAddressRecord> getPrimaryKey() {
		return com.breakfast.domain.Keys.KEY_T_BF_ADDRESS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.breakfast.domain.tables.records.TBfAddressRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.breakfast.domain.tables.records.TBfAddressRecord>>asList(com.breakfast.domain.Keys.KEY_T_BF_ADDRESS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.breakfast.domain.tables.TBfAddress as(java.lang.String alias) {
		return new com.breakfast.domain.tables.TBfAddress(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.breakfast.domain.tables.TBfAddress rename(java.lang.String name) {
		return new com.breakfast.domain.tables.TBfAddress(name, null);
	}
}
