/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables;

/**
 * This class is generated by jOOQ.
 *
 * 客服
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBfCustomerService extends org.jooq.impl.TableImpl<com.breakfast.domain.tables.records.TBfCustomerServiceRecord> {

	private static final long serialVersionUID = -359052647;

	/**
	 * The singleton instance of <code>breakfast.t_bf_customer_service</code>
	 */
	public static final com.breakfast.domain.tables.TBfCustomerService tBfCustomerService = new com.breakfast.domain.tables.TBfCustomerService();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.breakfast.domain.tables.records.TBfCustomerServiceRecord> getRecordType() {
		return com.breakfast.domain.tables.records.TBfCustomerServiceRecord.class;
	}

	/**
	 * The column <code>breakfast.t_bf_customer_service.user_id</code>.
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfCustomerServiceRecord, java.lang.String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * Create a <code>breakfast.t_bf_customer_service</code> table reference
	 */
	public TBfCustomerService() {
		this("t_bf_customer_service", null);
	}

	/**
	 * Create an aliased <code>breakfast.t_bf_customer_service</code> table reference
	 */
	public TBfCustomerService(java.lang.String alias) {
		this(alias, com.breakfast.domain.tables.TBfCustomerService.tBfCustomerService);
	}

	private TBfCustomerService(java.lang.String alias, org.jooq.Table<com.breakfast.domain.tables.records.TBfCustomerServiceRecord> aliased) {
		this(alias, aliased, null);
	}

	private TBfCustomerService(java.lang.String alias, org.jooq.Table<com.breakfast.domain.tables.records.TBfCustomerServiceRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.breakfast.domain.Breakfast.BREAKFAST, aliased, parameters, "客服");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.breakfast.domain.tables.records.TBfCustomerServiceRecord> getPrimaryKey() {
		return com.breakfast.domain.Keys.KEY_T_BF_CUSTOMER_SERVICE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.breakfast.domain.tables.records.TBfCustomerServiceRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.breakfast.domain.tables.records.TBfCustomerServiceRecord>>asList(com.breakfast.domain.Keys.KEY_T_BF_CUSTOMER_SERVICE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.breakfast.domain.tables.TBfCustomerService as(java.lang.String alias) {
		return new com.breakfast.domain.tables.TBfCustomerService(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.breakfast.domain.tables.TBfCustomerService rename(java.lang.String name) {
		return new com.breakfast.domain.tables.TBfCustomerService(name, null);
	}
}
