/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables;

/**
 * This class is generated by jOOQ.
 *
 * 食品表
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBfFood extends org.jooq.impl.TableImpl<com.breakfast.domain.tables.records.TBfFoodRecord> {

	private static final long serialVersionUID = 331475550;

	/**
	 * The singleton instance of <code>breakfast.t_bf_food</code>
	 */
	public static final com.breakfast.domain.tables.TBfFood tBfFood = new com.breakfast.domain.tables.TBfFood();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.breakfast.domain.tables.records.TBfFoodRecord> getRecordType() {
		return com.breakfast.domain.tables.records.TBfFoodRecord.class;
	}

	/**
	 * The column <code>breakfast.t_bf_food.food_id</code>. 主键
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfFoodRecord, java.lang.String> FOOD_ID = createField("food_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "主键");

	/**
	 * The column <code>breakfast.t_bf_food.food_name</code>. 名称
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfFoodRecord, java.lang.String> FOOD_NAME = createField("food_name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "名称");

	/**
	 * The column <code>breakfast.t_bf_food.cost</code>. 成本
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfFoodRecord, java.math.BigDecimal> COST = createField("cost", org.jooq.impl.SQLDataType.DECIMAL.precision(5, 3), this, "成本");

	/**
	 * The column <code>breakfast.t_bf_food.price</code>. 单价
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfFoodRecord, java.math.BigDecimal> PRICE = createField("price", org.jooq.impl.SQLDataType.DECIMAL.precision(5, 3), this, "单价");

	/**
	 * The column <code>breakfast.t_bf_food.unit</code>. 单位
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfFoodRecord, java.lang.String> UNIT = createField("unit", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "单位");

	/**
	 * The column <code>breakfast.t_bf_food.brief_intro</code>. 简介
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfFoodRecord, java.lang.String> BRIEF_INTRO = createField("brief_intro", org.jooq.impl.SQLDataType.VARCHAR.length(500), this, "简介");

	/**
	 * The column <code>breakfast.t_bf_food.status</code>. 状态：上架PUTAWAY、下架SOLD_PUT、废弃DISCARD
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfFoodRecord, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "状态：上架PUTAWAY、下架SOLD_PUT、废弃DISCARD");

	/**
	 * The column <code>breakfast.t_bf_food.food_count</code>. 假库存数
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfFoodRecord, java.lang.Integer> FOOD_COUNT = createField("food_count", org.jooq.impl.SQLDataType.INTEGER, this, "假库存数");

	/**
	 * The column <code>breakfast.t_bf_food.real_food_count</code>. 真实库存
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfFoodRecord, java.lang.Integer> REAL_FOOD_COUNT = createField("real_food_count", org.jooq.impl.SQLDataType.INTEGER, this, "真实库存");

	/**
	 * The column <code>breakfast.t_bf_food.small_pic_id</code>. 缩略图
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfFoodRecord, java.lang.String> SMALL_PIC_ID = createField("small_pic_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "缩略图");

	/**
	 * The column <code>breakfast.t_bf_food.orgin_pic_id</code>. 原图
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfFoodRecord, java.lang.String> ORGIN_PIC_ID = createField("orgin_pic_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "原图");

	/**
	 * The column <code>breakfast.t_bf_food.support_snap_up</code>. 是否支持抢购
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfFoodRecord, java.lang.Byte> SUPPORT_SNAP_UP = createField("support_snap_up", org.jooq.impl.SQLDataType.TINYINT, this, "是否支持抢购");

	/**
	 * The column <code>breakfast.t_bf_food.support_exchange</code>. 是否支持兑换
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfFoodRecord, java.lang.Byte> SUPPORT_EXCHANGE = createField("support_exchange", org.jooq.impl.SQLDataType.TINYINT, this, "是否支持兑换");

	/**
	 * The column <code>breakfast.t_bf_food.exchange_count</code>. 兑换所需黄豆数
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfFoodRecord, java.lang.Integer> EXCHANGE_COUNT = createField("exchange_count", org.jooq.impl.SQLDataType.INTEGER, this, "兑换所需黄豆数");

	/**
	 * Create a <code>breakfast.t_bf_food</code> table reference
	 */
	public TBfFood() {
		this("t_bf_food", null);
	}

	/**
	 * Create an aliased <code>breakfast.t_bf_food</code> table reference
	 */
	public TBfFood(java.lang.String alias) {
		this(alias, com.breakfast.domain.tables.TBfFood.tBfFood);
	}

	private TBfFood(java.lang.String alias, org.jooq.Table<com.breakfast.domain.tables.records.TBfFoodRecord> aliased) {
		this(alias, aliased, null);
	}

	private TBfFood(java.lang.String alias, org.jooq.Table<com.breakfast.domain.tables.records.TBfFoodRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.breakfast.domain.Breakfast.BREAKFAST, aliased, parameters, "食品表");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.breakfast.domain.tables.records.TBfFoodRecord> getPrimaryKey() {
		return com.breakfast.domain.Keys.KEY_T_BF_FOOD_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.breakfast.domain.tables.records.TBfFoodRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.breakfast.domain.tables.records.TBfFoodRecord>>asList(com.breakfast.domain.Keys.KEY_T_BF_FOOD_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.breakfast.domain.tables.TBfFood as(java.lang.String alias) {
		return new com.breakfast.domain.tables.TBfFood(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.breakfast.domain.tables.TBfFood rename(java.lang.String name) {
		return new com.breakfast.domain.tables.TBfFood(name, null);
	}
}
