/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables;

/**
 * This class is generated by jOOQ.
 *
 * 评分详情表
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBfGrade extends org.jooq.impl.TableImpl<com.breakfast.domain.tables.records.TBfGradeRecord> {

	private static final long serialVersionUID = -455452342;

	/**
	 * The singleton instance of <code>breakfast.t_bf_grade</code>
	 */
	public static final com.breakfast.domain.tables.TBfGrade tBfGrade = new com.breakfast.domain.tables.TBfGrade();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.breakfast.domain.tables.records.TBfGradeRecord> getRecordType() {
		return com.breakfast.domain.tables.records.TBfGradeRecord.class;
	}

	/**
	 * The column <code>breakfast.t_bf_grade.grade_id</code>.
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfGradeRecord, java.lang.String> GRADE_ID = createField("grade_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>breakfast.t_bf_grade.user_id</code>. 评分人
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfGradeRecord, java.lang.String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "评分人");

	/**
	 * The column <code>breakfast.t_bf_grade.target_type</code>. 评分对象类别
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfGradeRecord, java.lang.String> TARGET_TYPE = createField("target_type", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "评分对象类别");

	/**
	 * The column <code>breakfast.t_bf_grade.object_id</code>. 评分对象ID
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfGradeRecord, java.lang.String> OBJECT_ID = createField("object_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "评分对象ID");

	/**
	 * The column <code>breakfast.t_bf_grade.grade</code>. 评分
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfGradeRecord, java.lang.Integer> GRADE = createField("grade", org.jooq.impl.SQLDataType.INTEGER, this, "评分");

	/**
	 * The column <code>breakfast.t_bf_grade.create_time</code>. 创建时间
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfGradeRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建时间");

	/**
	 * The column <code>breakfast.t_bf_grade.last_modify_time</code>. 更新时间
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfGradeRecord, java.sql.Timestamp> LAST_MODIFY_TIME = createField("last_modify_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "更新时间");

	/**
	 * The column <code>breakfast.t_bf_grade.状态</code>. 状态
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfGradeRecord, java.lang.String> 状态 = createField("状态", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "状态");

	/**
	 * Create a <code>breakfast.t_bf_grade</code> table reference
	 */
	public TBfGrade() {
		this("t_bf_grade", null);
	}

	/**
	 * Create an aliased <code>breakfast.t_bf_grade</code> table reference
	 */
	public TBfGrade(java.lang.String alias) {
		this(alias, com.breakfast.domain.tables.TBfGrade.tBfGrade);
	}

	private TBfGrade(java.lang.String alias, org.jooq.Table<com.breakfast.domain.tables.records.TBfGradeRecord> aliased) {
		this(alias, aliased, null);
	}

	private TBfGrade(java.lang.String alias, org.jooq.Table<com.breakfast.domain.tables.records.TBfGradeRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.breakfast.domain.Breakfast.BREAKFAST, aliased, parameters, "评分详情表");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.breakfast.domain.tables.records.TBfGradeRecord> getPrimaryKey() {
		return com.breakfast.domain.Keys.KEY_T_BF_GRADE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.breakfast.domain.tables.records.TBfGradeRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.breakfast.domain.tables.records.TBfGradeRecord>>asList(com.breakfast.domain.Keys.KEY_T_BF_GRADE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.breakfast.domain.tables.TBfGrade as(java.lang.String alias) {
		return new com.breakfast.domain.tables.TBfGrade(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.breakfast.domain.tables.TBfGrade rename(java.lang.String name) {
		return new com.breakfast.domain.tables.TBfGrade(name, null);
	}
}
