/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables;

/**
 * This class is generated by jOOQ.
 *
 * 图片展示
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBfPhotoShow extends org.jooq.impl.TableImpl<com.breakfast.domain.tables.records.TBfPhotoShowRecord> {

	private static final long serialVersionUID = -2026430906;

	/**
	 * The singleton instance of <code>breakfast.t_bf_photo_show</code>
	 */
	public static final com.breakfast.domain.tables.TBfPhotoShow tBfPhotoShow = new com.breakfast.domain.tables.TBfPhotoShow();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.breakfast.domain.tables.records.TBfPhotoShowRecord> getRecordType() {
		return com.breakfast.domain.tables.records.TBfPhotoShowRecord.class;
	}

	/**
	 * The column <code>breakfast.t_bf_photo_show.photo_id</code>.
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfPhotoShowRecord, java.lang.String> PHOTO_ID = createField("photo_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>breakfast.t_bf_photo_show.file_id</code>. 图片文件ID
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfPhotoShowRecord, java.lang.String> FILE_ID = createField("file_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "图片文件ID");

	/**
	 * The column <code>breakfast.t_bf_photo_show.create_time</code>. 图片上传日期
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfPhotoShowRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "图片上传日期");

	/**
	 * The column <code>breakfast.t_bf_photo_show.valid_date</code>. 图片有效期
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfPhotoShowRecord, java.sql.Timestamp> VALID_DATE = createField("valid_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "图片有效期");

	/**
	 * The column <code>breakfast.t_bf_photo_show.createBy</code>. 上传机器编号
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfPhotoShowRecord, java.lang.String> CREATEBY = createField("createBy", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "上传机器编号");

	/**
	 * The column <code>breakfast.t_bf_photo_show.status</code>. 图片状态
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TBfPhotoShowRecord, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "图片状态");

	/**
	 * Create a <code>breakfast.t_bf_photo_show</code> table reference
	 */
	public TBfPhotoShow() {
		this("t_bf_photo_show", null);
	}

	/**
	 * Create an aliased <code>breakfast.t_bf_photo_show</code> table reference
	 */
	public TBfPhotoShow(java.lang.String alias) {
		this(alias, com.breakfast.domain.tables.TBfPhotoShow.tBfPhotoShow);
	}

	private TBfPhotoShow(java.lang.String alias, org.jooq.Table<com.breakfast.domain.tables.records.TBfPhotoShowRecord> aliased) {
		this(alias, aliased, null);
	}

	private TBfPhotoShow(java.lang.String alias, org.jooq.Table<com.breakfast.domain.tables.records.TBfPhotoShowRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.breakfast.domain.Breakfast.BREAKFAST, aliased, parameters, "图片展示");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.breakfast.domain.tables.records.TBfPhotoShowRecord> getPrimaryKey() {
		return com.breakfast.domain.Keys.KEY_T_BF_PHOTO_SHOW_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.breakfast.domain.tables.records.TBfPhotoShowRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.breakfast.domain.tables.records.TBfPhotoShowRecord>>asList(com.breakfast.domain.Keys.KEY_T_BF_PHOTO_SHOW_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.breakfast.domain.tables.TBfPhotoShow as(java.lang.String alias) {
		return new com.breakfast.domain.tables.TBfPhotoShow(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.breakfast.domain.tables.TBfPhotoShow rename(java.lang.String name) {
		return new com.breakfast.domain.tables.TBfPhotoShow(name, null);
	}
}
