/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables;

/**
 * This class is generated by jOOQ.
 *
 * 客服
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TCustomerService extends org.jooq.impl.TableImpl<com.breakfast.domain.tables.records.TCustomerServiceRecord> {

	private static final long serialVersionUID = 413472631;

	/**
	 * The singleton instance of <code>breakfast.t_bf_customer_service</code>
	 */
	public static final com.breakfast.domain.tables.TCustomerService CustomerService = new com.breakfast.domain.tables.TCustomerService();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.breakfast.domain.tables.records.TCustomerServiceRecord> getRecordType() {
		return com.breakfast.domain.tables.records.TCustomerServiceRecord.class;
	}

	/**
	 * The column <code>breakfast.t_bf_customer_service.user_id</code>.
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TCustomerServiceRecord, java.lang.String> userId = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>breakfast.t_bf_customer_service.create_time</code>. 创建时间
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TCustomerServiceRecord, org.joda.time.DateTime> createTime = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建时间", new com.breakfast.provider.DateTimeConverter());

	/**
	 * The column <code>breakfast.t_bf_customer_service.create_by</code>. 创建人
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TCustomerServiceRecord, java.lang.String> createBy = createField("create_by", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "创建人");

	/**
	 * The column <code>breakfast.t_bf_customer_service.last_modify_time</code>. 最后修改时间
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TCustomerServiceRecord, org.joda.time.DateTime> lastModifyTime = createField("last_modify_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "最后修改时间", new com.breakfast.provider.DateTimeConverter());

	/**
	 * The column <code>breakfast.t_bf_customer_service.last_modify_by</code>. 最后修改人
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TCustomerServiceRecord, java.lang.String> lastModifyBy = createField("last_modify_by", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "最后修改人");

	/**
	 * The column <code>breakfast.t_bf_customer_service.opt_time</code>. 操作时间
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TCustomerServiceRecord, java.lang.Long> optTime = createField("opt_time", org.jooq.impl.SQLDataType.BIGINT, this, "操作时间");

	/**
	 * Create a <code>breakfast.t_bf_customer_service</code> table reference
	 */
	public TCustomerService() {
		this("t_bf_customer_service", null);
	}

	/**
	 * Create an aliased <code>breakfast.t_bf_customer_service</code> table reference
	 */
	public TCustomerService(java.lang.String alias) {
		this(alias, com.breakfast.domain.tables.TCustomerService.CustomerService);
	}

	private TCustomerService(java.lang.String alias, org.jooq.Table<com.breakfast.domain.tables.records.TCustomerServiceRecord> aliased) {
		this(alias, aliased, null);
	}

	private TCustomerService(java.lang.String alias, org.jooq.Table<com.breakfast.domain.tables.records.TCustomerServiceRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.breakfast.domain.Breakfast.breakfast, aliased, parameters, "客服");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.breakfast.domain.tables.records.TCustomerServiceRecord> getPrimaryKey() {
		return com.breakfast.domain.Keys.keyTBfCustomerServicePrimary;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.breakfast.domain.tables.records.TCustomerServiceRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.breakfast.domain.tables.records.TCustomerServiceRecord>>asList(com.breakfast.domain.Keys.keyTBfCustomerServicePrimary);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.breakfast.domain.tables.TCustomerService as(java.lang.String alias) {
		return new com.breakfast.domain.tables.TCustomerService(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.breakfast.domain.tables.TCustomerService rename(java.lang.String name) {
		return new com.breakfast.domain.tables.TCustomerService(name, null);
	}
}
