/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables;

/**
 * This class is generated by jOOQ.
 *
 * 元素定义表
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TElement extends org.jooq.impl.TableImpl<com.breakfast.domain.tables.records.TElementRecord> {

	private static final long serialVersionUID = -1777389159;

	/**
	 * The singleton instance of <code>breakfast.t_bf_element</code>
	 */
	public static final com.breakfast.domain.tables.TElement Element = new com.breakfast.domain.tables.TElement();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<com.breakfast.domain.tables.records.TElementRecord> getRecordType() {
		return com.breakfast.domain.tables.records.TElementRecord.class;
	}

	/**
	 * The column <code>breakfast.t_bf_element.element_id</code>.
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TElementRecord, String> elementId = createField("element_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>breakfast.t_bf_element.element_name</code>. 元素名称
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TElementRecord, String> elementName = createField("element_name", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "元素名称");

	/**
	 * The column <code>breakfast.t_bf_element.unit</code>. 元素计量单位
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TElementRecord, String> unit = createField("unit", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "元素计量单位");

	/**
	 * Create a <code>breakfast.t_bf_element</code> table reference
	 */
	public TElement() {
		this("t_bf_element", null);
	}

	/**
	 * Create an aliased <code>breakfast.t_bf_element</code> table reference
	 */
	public TElement(String alias) {
		this(alias, com.breakfast.domain.tables.TElement.Element);
	}

	private TElement(String alias, org.jooq.Table<com.breakfast.domain.tables.records.TElementRecord> aliased) {
		this(alias, aliased, null);
	}

	private TElement(String alias, org.jooq.Table<com.breakfast.domain.tables.records.TElementRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.breakfast.domain.Breakfast.breakfast, aliased, parameters, "元素定义表");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.breakfast.domain.tables.records.TElementRecord> getPrimaryKey() {
		return com.breakfast.domain.Keys.keyTBfElementPrimary;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.breakfast.domain.tables.records.TElementRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.breakfast.domain.tables.records.TElementRecord>>asList(com.breakfast.domain.Keys.keyTBfElementPrimary);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.breakfast.domain.tables.TElement as(String alias) {
		return new com.breakfast.domain.tables.TElement(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.breakfast.domain.tables.TElement rename(String name) {
		return new com.breakfast.domain.tables.TElement(name, null);
	}
}
