/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables;

/**
 * This class is generated by jOOQ.
 *
 * 评分详情表
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TGrade extends org.jooq.impl.TableImpl<com.breakfast.domain.tables.records.TGradeRecord> {

	private static final long serialVersionUID = -1440777932;

	/**
	 * The singleton instance of <code>breakfast.t_bf_grade</code>
	 */
	public static final com.breakfast.domain.tables.TGrade Grade = new com.breakfast.domain.tables.TGrade();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.breakfast.domain.tables.records.TGradeRecord> getRecordType() {
		return com.breakfast.domain.tables.records.TGradeRecord.class;
	}

	/**
	 * The column <code>breakfast.t_bf_grade.grade_id</code>.
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TGradeRecord, java.lang.String> gradeId = createField("grade_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>breakfast.t_bf_grade.user_id</code>. 评分人
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TGradeRecord, java.lang.String> userId = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "评分人");

	/**
	 * The column <code>breakfast.t_bf_grade.target_type</code>. 评分对象类别
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TGradeRecord, java.lang.String> targetType = createField("target_type", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "评分对象类别");

	/**
	 * The column <code>breakfast.t_bf_grade.target_id</code>. 评分对象ID
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TGradeRecord, java.lang.String> targetId = createField("target_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "评分对象ID");

	/**
	 * The column <code>breakfast.t_bf_grade.grade</code>. 评分
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TGradeRecord, java.lang.Integer> grade = createField("grade", org.jooq.impl.SQLDataType.INTEGER, this, "评分");

	/**
	 * The column <code>breakfast.t_bf_grade.status</code>. 状态
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TGradeRecord, java.lang.String> status = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "状态");

	/**
	 * The column <code>breakfast.t_bf_grade.create_time</code>. 创建时间
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TGradeRecord, org.joda.time.DateTime> createTime = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建时间", new com.breakfast.provider.DateTimeConverter());

	/**
	 * The column <code>breakfast.t_bf_grade.create_by</code>. 创建人
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TGradeRecord, java.lang.String> createBy = createField("create_by", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "创建人");

	/**
	 * The column <code>breakfast.t_bf_grade.last_modify_time</code>. 最后修改时间
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TGradeRecord, org.joda.time.DateTime> lastModifyTime = createField("last_modify_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "最后修改时间", new com.breakfast.provider.DateTimeConverter());

	/**
	 * The column <code>breakfast.t_bf_grade.last_modify_by</code>. 最后修改人
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TGradeRecord, java.lang.String> lastModifyBy = createField("last_modify_by", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "最后修改人");

	/**
	 * The column <code>breakfast.t_bf_grade.opt_time</code>. 操作时间
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TGradeRecord, java.lang.Long> optTime = createField("opt_time", org.jooq.impl.SQLDataType.BIGINT, this, "操作时间");

	/**
	 * Create a <code>breakfast.t_bf_grade</code> table reference
	 */
	public TGrade() {
		this("t_bf_grade", null);
	}

	/**
	 * Create an aliased <code>breakfast.t_bf_grade</code> table reference
	 */
	public TGrade(java.lang.String alias) {
		this(alias, com.breakfast.domain.tables.TGrade.Grade);
	}

	private TGrade(java.lang.String alias, org.jooq.Table<com.breakfast.domain.tables.records.TGradeRecord> aliased) {
		this(alias, aliased, null);
	}

	private TGrade(java.lang.String alias, org.jooq.Table<com.breakfast.domain.tables.records.TGradeRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.breakfast.domain.Breakfast.breakfast, aliased, parameters, "评分详情表");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.breakfast.domain.tables.records.TGradeRecord> getPrimaryKey() {
		return com.breakfast.domain.Keys.keyTBfGradePrimary;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.breakfast.domain.tables.records.TGradeRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.breakfast.domain.tables.records.TGradeRecord>>asList(com.breakfast.domain.Keys.keyTBfGradePrimary);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.breakfast.domain.tables.TGrade as(java.lang.String alias) {
		return new com.breakfast.domain.tables.TGrade(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.breakfast.domain.tables.TGrade rename(java.lang.String name) {
		return new com.breakfast.domain.tables.TGrade(name, null);
	}
}
