/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables;

/**
 * This class is generated by jOOQ.
 *
 * 订单详情表
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TOrderDetail extends org.jooq.impl.TableImpl<com.breakfast.domain.tables.records.TOrderDetailRecord> {

	private static final long serialVersionUID = 617205966;

	/**
	 * The singleton instance of <code>breakfast.t_bf_order_detail</code>
	 */
	public static final com.breakfast.domain.tables.TOrderDetail OrderDetail = new com.breakfast.domain.tables.TOrderDetail();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.breakfast.domain.tables.records.TOrderDetailRecord> getRecordType() {
		return com.breakfast.domain.tables.records.TOrderDetailRecord.class;
	}

	/**
	 * The column <code>breakfast.t_bf_order_detail.detail_id</code>.
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TOrderDetailRecord, java.lang.String> detailId = createField("detail_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>breakfast.t_bf_order_detail.order_id</code>. 订单ID
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TOrderDetailRecord, java.lang.String> orderId = createField("order_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "订单ID");

	/**
	 * The column <code>breakfast.t_bf_order_detail.food_obj_id</code>. 单品/套餐 ID
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TOrderDetailRecord, java.lang.String> foodObjId = createField("food_obj_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "单品/套餐 ID");

	/**
	 * The column <code>breakfast.t_bf_order_detail.food_obj_count</code>. 数量
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TOrderDetailRecord, java.lang.Integer> foodObjCount = createField("food_obj_count", org.jooq.impl.SQLDataType.INTEGER, this, "数量");

	/**
	 * The column <code>breakfast.t_bf_order_detail.food_obj_type</code>. 单品/套餐
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TOrderDetailRecord, java.lang.String> foodObjType = createField("food_obj_type", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "单品/套餐");

	/**
	 * The column <code>breakfast.t_bf_order_detail.create_time</code>. 创建时间
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TOrderDetailRecord, org.joda.time.DateTime> createTime = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建时间", new com.breakfast.provider.DateTimeConverter());

	/**
	 * The column <code>breakfast.t_bf_order_detail.create_by</code>. 创建人
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TOrderDetailRecord, java.lang.String> createBy = createField("create_by", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "创建人");

	/**
	 * The column <code>breakfast.t_bf_order_detail.last_modify_time</code>. 最后修改时间
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TOrderDetailRecord, org.joda.time.DateTime> lastModifyTime = createField("last_modify_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "最后修改时间", new com.breakfast.provider.DateTimeConverter());

	/**
	 * The column <code>breakfast.t_bf_order_detail.last_modify_by</code>. 最后修改人
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TOrderDetailRecord, java.lang.String> lastModifyBy = createField("last_modify_by", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "最后修改人");

	/**
	 * The column <code>breakfast.t_bf_order_detail.opt_time</code>. 操作时间
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TOrderDetailRecord, java.lang.Long> optTime = createField("opt_time", org.jooq.impl.SQLDataType.BIGINT, this, "操作时间");

	/**
	 * Create a <code>breakfast.t_bf_order_detail</code> table reference
	 */
	public TOrderDetail() {
		this("t_bf_order_detail", null);
	}

	/**
	 * Create an aliased <code>breakfast.t_bf_order_detail</code> table reference
	 */
	public TOrderDetail(java.lang.String alias) {
		this(alias, com.breakfast.domain.tables.TOrderDetail.OrderDetail);
	}

	private TOrderDetail(java.lang.String alias, org.jooq.Table<com.breakfast.domain.tables.records.TOrderDetailRecord> aliased) {
		this(alias, aliased, null);
	}

	private TOrderDetail(java.lang.String alias, org.jooq.Table<com.breakfast.domain.tables.records.TOrderDetailRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.breakfast.domain.Breakfast.breakfast, aliased, parameters, "订单详情表");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.breakfast.domain.tables.records.TOrderDetailRecord> getPrimaryKey() {
		return com.breakfast.domain.Keys.keyTBfOrderDetailPrimary;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.breakfast.domain.tables.records.TOrderDetailRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.breakfast.domain.tables.records.TOrderDetailRecord>>asList(com.breakfast.domain.Keys.keyTBfOrderDetailPrimary);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.breakfast.domain.tables.TOrderDetail as(java.lang.String alias) {
		return new com.breakfast.domain.tables.TOrderDetail(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.breakfast.domain.tables.TOrderDetail rename(java.lang.String name) {
		return new com.breakfast.domain.tables.TOrderDetail(name, null);
	}
}
