/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables;

/**
 * This class is generated by jOOQ.
 *
 * 分发红包表
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSendCoupon extends org.jooq.impl.TableImpl<com.breakfast.domain.tables.records.TSendCouponRecord> {

	private static final long serialVersionUID = 979715924;

	/**
	 * The singleton instance of <code>breakfast.t_bf_send_coupon</code>
	 */
	public static final com.breakfast.domain.tables.TSendCoupon SendCoupon = new com.breakfast.domain.tables.TSendCoupon();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<com.breakfast.domain.tables.records.TSendCouponRecord> getRecordType() {
		return com.breakfast.domain.tables.records.TSendCouponRecord.class;
	}

	/**
	 * The column <code>breakfast.t_bf_send_coupon.send_coupon_id</code>.
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSendCouponRecord, String> sendCouponId = createField("send_coupon_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>breakfast.t_bf_send_coupon.create_time</code>. 发放时间
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSendCouponRecord, org.joda.time.DateTime> createTime = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "发放时间", new com.breakfast.provider.DateTimeConverter());

	/**
	 * The column <code>breakfast.t_bf_send_coupon.end_time</code>. 截止日期
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSendCouponRecord, org.joda.time.DateTime> endTime = createField("end_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "截止日期", new com.breakfast.provider.DateTimeConverter());

	/**
	 * The column <code>breakfast.t_bf_send_coupon.price</code>. 价值
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSendCouponRecord, java.math.BigDecimal> price = createField("price", org.jooq.impl.SQLDataType.DECIMAL.precision(8, 3), this, "价值");

	/**
	 * The column <code>breakfast.t_bf_send_coupon.source</code>. 发放人
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSendCouponRecord, String> source = createField("source", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "发放人");

	/**
	 * The column <code>breakfast.t_bf_send_coupon.status</code>. 状态
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSendCouponRecord, String> status = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "状态");

	/**
	 * The column <code>breakfast.t_bf_send_coupon.brief_intro</code>. 简介
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSendCouponRecord, String> briefIntro = createField("brief_intro", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "简介");

	/**
	 * The column <code>breakfast.t_bf_send_coupon.num</code>.
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSendCouponRecord, Integer> num = createField("num", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>breakfast.t_bf_send_coupon.url</code>.
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSendCouponRecord, String> url = createField("url", org.jooq.impl.SQLDataType.VARCHAR.length(300), this, "");

	/**
	 * The column <code>breakfast.t_bf_send_coupon.create_by</code>. 创建人
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSendCouponRecord, String> createBy = createField("create_by", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "创建人");

	/**
	 * The column <code>breakfast.t_bf_send_coupon.last_modify_time</code>. 最后修改时间
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSendCouponRecord, org.joda.time.DateTime> lastModifyTime = createField("last_modify_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "最后修改时间", new com.breakfast.provider.DateTimeConverter());

	/**
	 * The column <code>breakfast.t_bf_send_coupon.last_modify_by</code>. 最后修改人
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSendCouponRecord, String> lastModifyBy = createField("last_modify_by", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "最后修改人");

	/**
	 * The column <code>breakfast.t_bf_send_coupon.opt_time</code>. 操作时间
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSendCouponRecord, Long> optTime = createField("opt_time", org.jooq.impl.SQLDataType.BIGINT, this, "操作时间");

	/**
	 * Create a <code>breakfast.t_bf_send_coupon</code> table reference
	 */
	public TSendCoupon() {
		this("t_bf_send_coupon", null);
	}

	/**
	 * Create an aliased <code>breakfast.t_bf_send_coupon</code> table reference
	 */
	public TSendCoupon(String alias) {
		this(alias, com.breakfast.domain.tables.TSendCoupon.SendCoupon);
	}

	private TSendCoupon(String alias, org.jooq.Table<com.breakfast.domain.tables.records.TSendCouponRecord> aliased) {
		this(alias, aliased, null);
	}

	private TSendCoupon(String alias, org.jooq.Table<com.breakfast.domain.tables.records.TSendCouponRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.breakfast.domain.Breakfast.breakfast, aliased, parameters, "分发红包表");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.breakfast.domain.tables.records.TSendCouponRecord> getPrimaryKey() {
		return com.breakfast.domain.Keys.keyTBfSendCouponPrimary;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.breakfast.domain.tables.records.TSendCouponRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.breakfast.domain.tables.records.TSendCouponRecord>>asList(com.breakfast.domain.Keys.keyTBfSendCouponPrimary);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.breakfast.domain.tables.TSendCoupon as(String alias) {
		return new com.breakfast.domain.tables.TSendCoupon(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.breakfast.domain.tables.TSendCoupon rename(String name) {
		return new com.breakfast.domain.tables.TSendCoupon(name, null);
	}
}
