/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables;

/**
 * This class is generated by jOOQ.
 *
 * 套餐食品
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSetFoods extends org.jooq.impl.TableImpl<com.breakfast.domain.tables.records.TSetFoodsRecord> {

	private static final long serialVersionUID = 428580699;

	/**
	 * The singleton instance of <code>breakfast.t_bf_set_foods</code>
	 */
	public static final com.breakfast.domain.tables.TSetFoods SetFoods = new com.breakfast.domain.tables.TSetFoods();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.breakfast.domain.tables.records.TSetFoodsRecord> getRecordType() {
		return com.breakfast.domain.tables.records.TSetFoodsRecord.class;
	}

	/**
	 * The column <code>breakfast.t_bf_set_foods.set_foods_id</code>.
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetFoodsRecord, java.lang.String> setFoodsId = createField("set_foods_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>breakfast.t_bf_set_foods.set_meal_id</code>. 套餐ID
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetFoodsRecord, java.lang.String> setMealId = createField("set_meal_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "套餐ID");

	/**
	 * The column <code>breakfast.t_bf_set_foods.food_id</code>. 食品Id
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetFoodsRecord, java.lang.String> foodId = createField("food_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "食品Id");

	/**
	 * The column <code>breakfast.t_bf_set_foods.food_count</code>. 食品数量
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetFoodsRecord, java.lang.Integer> foodCount = createField("food_count", org.jooq.impl.SQLDataType.INTEGER, this, "食品数量");

	/**
	 * The column <code>breakfast.t_bf_set_foods.create_time</code>. 创建时间
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetFoodsRecord, org.joda.time.DateTime> createTime = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建时间", new com.breakfast.provider.DateTimeConverter());

	/**
	 * The column <code>breakfast.t_bf_set_foods.create_by</code>. 创建人
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetFoodsRecord, java.lang.String> createBy = createField("create_by", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "创建人");

	/**
	 * The column <code>breakfast.t_bf_set_foods.last_modify_time</code>. 最后修改时间
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetFoodsRecord, org.joda.time.DateTime> lastModifyTime = createField("last_modify_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "最后修改时间", new com.breakfast.provider.DateTimeConverter());

	/**
	 * The column <code>breakfast.t_bf_set_foods.last_modify_by</code>. 最后修改人
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetFoodsRecord, java.lang.String> lastModifyBy = createField("last_modify_by", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "最后修改人");

	/**
	 * The column <code>breakfast.t_bf_set_foods.opt_time</code>. 操作时间
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetFoodsRecord, java.lang.Long> optTime = createField("opt_time", org.jooq.impl.SQLDataType.BIGINT, this, "操作时间");

	/**
	 * Create a <code>breakfast.t_bf_set_foods</code> table reference
	 */
	public TSetFoods() {
		this("t_bf_set_foods", null);
	}

	/**
	 * Create an aliased <code>breakfast.t_bf_set_foods</code> table reference
	 */
	public TSetFoods(java.lang.String alias) {
		this(alias, com.breakfast.domain.tables.TSetFoods.SetFoods);
	}

	private TSetFoods(java.lang.String alias, org.jooq.Table<com.breakfast.domain.tables.records.TSetFoodsRecord> aliased) {
		this(alias, aliased, null);
	}

	private TSetFoods(java.lang.String alias, org.jooq.Table<com.breakfast.domain.tables.records.TSetFoodsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.breakfast.domain.Breakfast.breakfast, aliased, parameters, "套餐食品");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.breakfast.domain.tables.records.TSetFoodsRecord> getPrimaryKey() {
		return com.breakfast.domain.Keys.keyTBfSetFoodsPrimary;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.breakfast.domain.tables.records.TSetFoodsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.breakfast.domain.tables.records.TSetFoodsRecord>>asList(com.breakfast.domain.Keys.keyTBfSetFoodsPrimary);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.breakfast.domain.tables.TSetFoods as(java.lang.String alias) {
		return new com.breakfast.domain.tables.TSetFoods(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.breakfast.domain.tables.TSetFoods rename(java.lang.String name) {
		return new com.breakfast.domain.tables.TSetFoods(name, null);
	}
}
