/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables;

/**
 * This class is generated by jOOQ.
 *
 * 套餐表
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSetMeal extends org.jooq.impl.TableImpl<com.breakfast.domain.tables.records.TSetMealRecord> {

	private static final long serialVersionUID = 101149934;

	/**
	 * The singleton instance of <code>breakfast.t_bf_set_meal</code>
	 */
	public static final com.breakfast.domain.tables.TSetMeal SetMeal = new com.breakfast.domain.tables.TSetMeal();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.breakfast.domain.tables.records.TSetMealRecord> getRecordType() {
		return com.breakfast.domain.tables.records.TSetMealRecord.class;
	}

	/**
	 * The column <code>breakfast.t_bf_set_meal.set_meal_id</code>.
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetMealRecord, java.lang.String> setMealId = createField("set_meal_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>breakfast.t_bf_set_meal.set_name</code>. 套餐名称
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetMealRecord, java.lang.String> setName = createField("set_name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "套餐名称");

	/**
	 * The column <code>breakfast.t_bf_set_meal.introduce</code>. 套餐说明
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetMealRecord, java.lang.String> introduce = createField("introduce", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "套餐说明");

	/**
	 * The column <code>breakfast.t_bf_set_meal.start_time</code>. 套餐开始日期
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetMealRecord, org.joda.time.DateTime> startTime = createField("start_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "套餐开始日期", new com.breakfast.provider.DateTimeConverter());

	/**
	 * The column <code>breakfast.t_bf_set_meal.end_time</code>. 套餐结束日期
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetMealRecord, org.joda.time.DateTime> endTime = createField("end_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "套餐结束日期", new com.breakfast.provider.DateTimeConverter());

	/**
	 * The column <code>breakfast.t_bf_set_meal.price</code>. 套餐价格
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetMealRecord, java.math.BigDecimal> price = createField("price", org.jooq.impl.SQLDataType.DECIMAL.precision(7, 3), this, "套餐价格");

	/**
	 * The column <code>breakfast.t_bf_set_meal.privilege</code>. 套餐优惠
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetMealRecord, java.math.BigDecimal> privilege = createField("privilege", org.jooq.impl.SQLDataType.DECIMAL.precision(7, 3), this, "套餐优惠");

	/**
	 * The column <code>breakfast.t_bf_set_meal.status</code>. 状态：上架PUTAWAY、下架SOLD_PUT、废弃DISCARD
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetMealRecord, java.lang.String> status = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "状态：上架PUTAWAY、下架SOLD_PUT、废弃DISCARD");

	/**
	 * The column <code>breakfast.t_bf_set_meal.food_count</code>. 假库存数
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetMealRecord, java.lang.Integer> foodCount = createField("food_count", org.jooq.impl.SQLDataType.INTEGER, this, "假库存数");

	/**
	 * The column <code>breakfast.t_bf_set_meal.real_food_count</code>. 真实库存
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetMealRecord, java.lang.Integer> realFoodCount = createField("real_food_count", org.jooq.impl.SQLDataType.INTEGER, this, "真实库存");

	/**
	 * The column <code>breakfast.t_bf_set_meal.small_pic_id</code>. 缩略图
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetMealRecord, java.lang.String> smallPicId = createField("small_pic_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "缩略图");

	/**
	 * The column <code>breakfast.t_bf_set_meal.orgin_pic_id</code>. 原图
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetMealRecord, java.lang.String> orginPicId = createField("orgin_pic_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "原图");

	/**
	 * The column <code>breakfast.t_bf_set_meal.support_snap_up</code>. 是否支持抢购
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetMealRecord, java.lang.Byte> supportSnapUp = createField("support_snap_up", org.jooq.impl.SQLDataType.TINYINT, this, "是否支持抢购");

	/**
	 * The column <code>breakfast.t_bf_set_meal.support_exchange</code>. 是否支持兑换
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetMealRecord, java.lang.Byte> supportExchange = createField("support_exchange", org.jooq.impl.SQLDataType.TINYINT, this, "是否支持兑换");

	/**
	 * The column <code>breakfast.t_bf_set_meal.exchange_count</code>. 兑换所需黄豆数
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetMealRecord, java.lang.Integer> exchangeCount = createField("exchange_count", org.jooq.impl.SQLDataType.INTEGER, this, "兑换所需黄豆数");

	/**
	 * The column <code>breakfast.t_bf_set_meal.show_order</code>. 显示顺序
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetMealRecord, java.lang.Integer> showOrder = createField("show_order", org.jooq.impl.SQLDataType.INTEGER, this, "显示顺序");

	/**
	 * The column <code>breakfast.t_bf_set_meal.sale_time</code>.
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetMealRecord, java.sql.Timestamp> saleTime = createField("sale_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>breakfast.t_bf_set_meal.create_time</code>. 创建时间
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetMealRecord, org.joda.time.DateTime> createTime = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建时间", new com.breakfast.provider.DateTimeConverter());

	/**
	 * The column <code>breakfast.t_bf_set_meal.create_by</code>. 创建人
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetMealRecord, java.lang.String> createBy = createField("create_by", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "创建人");

	/**
	 * The column <code>breakfast.t_bf_set_meal.last_modify_time</code>. 最后修改时间
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetMealRecord, org.joda.time.DateTime> lastModifyTime = createField("last_modify_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "最后修改时间", new com.breakfast.provider.DateTimeConverter());

	/**
	 * The column <code>breakfast.t_bf_set_meal.last_modify_by</code>. 最后修改人
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetMealRecord, java.lang.String> lastModifyBy = createField("last_modify_by", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "最后修改人");

	/**
	 * The column <code>breakfast.t_bf_set_meal.opt_time</code>. 操作时间
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.TSetMealRecord, java.lang.Long> optTime = createField("opt_time", org.jooq.impl.SQLDataType.BIGINT, this, "操作时间");

	/**
	 * Create a <code>breakfast.t_bf_set_meal</code> table reference
	 */
	public TSetMeal() {
		this("t_bf_set_meal", null);
	}

	/**
	 * Create an aliased <code>breakfast.t_bf_set_meal</code> table reference
	 */
	public TSetMeal(java.lang.String alias) {
		this(alias, com.breakfast.domain.tables.TSetMeal.SetMeal);
	}

	private TSetMeal(java.lang.String alias, org.jooq.Table<com.breakfast.domain.tables.records.TSetMealRecord> aliased) {
		this(alias, aliased, null);
	}

	private TSetMeal(java.lang.String alias, org.jooq.Table<com.breakfast.domain.tables.records.TSetMealRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.breakfast.domain.Breakfast.breakfast, aliased, parameters, "套餐表");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.breakfast.domain.tables.records.TSetMealRecord> getPrimaryKey() {
		return com.breakfast.domain.Keys.keyTBfSetMealPrimary;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.breakfast.domain.tables.records.TSetMealRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.breakfast.domain.tables.records.TSetMealRecord>>asList(com.breakfast.domain.Keys.keyTBfSetMealPrimary);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.breakfast.domain.tables.TSetMeal as(java.lang.String alias) {
		return new com.breakfast.domain.tables.TSetMeal(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.breakfast.domain.tables.TSetMeal rename(java.lang.String name) {
		return new com.breakfast.domain.tables.TSetMeal(name, null);
	}
}
