/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain.tables;

/**
 * This class is generated by jOOQ.
 *
 * 人员表
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User extends org.jooq.impl.TableImpl<com.breakfast.domain.tables.records.UserRecord> {

	private static final long serialVersionUID = 340773696;

	/**
	 * The singleton instance of <code>breakfast.t_bf_user</code>
	 */
	public static final com.breakfast.domain.tables.User User = new com.breakfast.domain.tables.User();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.breakfast.domain.tables.records.UserRecord> getRecordType() {
		return com.breakfast.domain.tables.records.UserRecord.class;
	}

	/**
	 * The column <code>breakfast.t_bf_user.user_id</code>.
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.UserRecord, java.lang.String> userId = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>breakfast.t_bf_user.login_name</code>. 用户名
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.UserRecord, java.lang.String> loginName = createField("login_name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "用户名");

	/**
	 * The column <code>breakfast.t_bf_user.password</code>. 密码
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.UserRecord, java.lang.String> password = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "密码");

	/**
	 * The column <code>breakfast.t_bf_user.status</code>. 状态
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.UserRecord, java.lang.String> status = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "状态");

	/**
	 * The column <code>breakfast.t_bf_user.user_name</code>. 姓名
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.UserRecord, java.lang.String> userName = createField("user_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "姓名");

	/**
	 * The column <code>breakfast.t_bf_user.mobile</code>. 手机号
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.UserRecord, java.lang.String> mobile = createField("mobile", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "手机号");

	/**
	 * The column <code>breakfast.t_bf_user.weixin</code>. 微信号
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.UserRecord, java.lang.String> weixin = createField("weixin", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "微信号");

	/**
	 * The column <code>breakfast.t_bf_user.qq</code>.
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.UserRecord, java.lang.String> qq = createField("qq", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>breakfast.t_bf_user.create_time</code>. 注册日期
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.UserRecord, java.sql.Timestamp> createTime = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "注册日期");

	/**
	 * The column <code>breakfast.t_bf_user.create_way</code>. 注册方式
	 */
	public final org.jooq.TableField<com.breakfast.domain.tables.records.UserRecord, java.lang.String> createWay = createField("create_way", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "注册方式");

	/**
	 * Create a <code>breakfast.t_bf_user</code> table reference
	 */
	public User() {
		this("t_bf_user", null);
	}

	/**
	 * Create an aliased <code>breakfast.t_bf_user</code> table reference
	 */
	public User(java.lang.String alias) {
		this(alias, com.breakfast.domain.tables.User.User);
	}

	private User(java.lang.String alias, org.jooq.Table<com.breakfast.domain.tables.records.UserRecord> aliased) {
		this(alias, aliased, null);
	}

	private User(java.lang.String alias, org.jooq.Table<com.breakfast.domain.tables.records.UserRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.breakfast.domain.Breakfast.breakfast, aliased, parameters, "人员表");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.breakfast.domain.tables.records.UserRecord> getPrimaryKey() {
		return com.breakfast.domain.Keys.keyTBfUserPrimary;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.breakfast.domain.tables.records.UserRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.breakfast.domain.tables.records.UserRecord>>asList(com.breakfast.domain.Keys.keyTBfUserPrimary);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.breakfast.domain.tables.User as(java.lang.String alias) {
		return new com.breakfast.domain.tables.User(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.breakfast.domain.tables.User rename(java.lang.String name) {
		return new com.breakfast.domain.tables.User(name, null);
	}
}
