/**
 * This class is generated by jOOQ
 */
package com.breakfast.domain;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in breakfast
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * 地址表
	 */
	public static final com.breakfast.domain.tables.TAddress Address = com.breakfast.domain.tables.TAddress.Address;

	/**
	 * 代金券表
	 */
	public static final com.breakfast.domain.tables.TCoupon Coupon = com.breakfast.domain.tables.TCoupon.Coupon;

	/**
	 * 客服
	 */
	public static final com.breakfast.domain.tables.TCustomerService CustomerService = com.breakfast.domain.tables.TCustomerService.CustomerService;

	/**
	 * 用户定制详情
	 */
	public static final com.breakfast.domain.tables.TCustomOrderDetail CustomOrderDetail = com.breakfast.domain.tables.TCustomOrderDetail.CustomOrderDetail;

	/**
	 * 元素定义表
	 */
	public static final com.breakfast.domain.tables.TElement Element = com.breakfast.domain.tables.TElement.Element;

	/**
	 * 元素含量表
	 */
	public static final com.breakfast.domain.tables.TElementContent ElementContent = com.breakfast.domain.tables.TElementContent.ElementContent;

	/**
	 * 订单配送表
	 */
	public static final com.breakfast.domain.tables.TExpress Express = com.breakfast.domain.tables.TExpress.Express;

	/**
	 * 评价反馈表
	 */
	public static final com.breakfast.domain.tables.TFeedback Feedback = com.breakfast.domain.tables.TFeedback.Feedback;

	/**
	 * 文件表
	 */
	public static final com.breakfast.domain.tables.TFile File = com.breakfast.domain.tables.TFile.File;

	/**
	 * 食品表
	 */
	public static final com.breakfast.domain.tables.TFood Food = com.breakfast.domain.tables.TFood.Food;

	/**
	 * 用户定制表
	 */
	public static final com.breakfast.domain.tables.TFoodCustom FoodCustom = com.breakfast.domain.tables.TFoodCustom.FoodCustom;

	/**
	 * 原材料食品中间表
	 */
	public static final com.breakfast.domain.tables.TFoodDetail FoodDetail = com.breakfast.domain.tables.TFoodDetail.FoodDetail;

	/**
	 * 评分详情表
	 */
	public static final com.breakfast.domain.tables.TGrade Grade = com.breakfast.domain.tables.TGrade.Grade;

	/**
	 * 公告信息表
	 */
	public static final com.breakfast.domain.tables.TInformation Information = com.breakfast.domain.tables.TInformation.Information;

	/**
	 * 聊天信息表
	 */
	public static final com.breakfast.domain.tables.TMessage Message = com.breakfast.domain.tables.TMessage.Message;

	/**
	 * 订单表
	 */
	public static final com.breakfast.domain.tables.TOrder Order = com.breakfast.domain.tables.TOrder.Order;

	/**
	 * 订单详情表
	 */
	public static final com.breakfast.domain.tables.TOrderDetail OrderDetail = com.breakfast.domain.tables.TOrderDetail.OrderDetail;

	/**
	 * 图片展示
	 */
	public static final com.breakfast.domain.tables.TPhotoShow PhotoShow = com.breakfast.domain.tables.TPhotoShow.PhotoShow;

	/**
	 * 供应商
	 */
	public static final com.breakfast.domain.tables.TProvider Provider = com.breakfast.domain.tables.TProvider.Provider;

	/**
	 * 原材料表
	 */
	public static final com.breakfast.domain.tables.TRawMaterial RawMaterial = com.breakfast.domain.tables.TRawMaterial.RawMaterial;

	/**
	 * 分发红包表
	 */
	public static final com.breakfast.domain.tables.TSendCoupon SendCoupon = com.breakfast.domain.tables.TSendCoupon.SendCoupon;

	/**
	 * 套餐食品
	 */
	public static final com.breakfast.domain.tables.TSetFoods SetFoods = com.breakfast.domain.tables.TSetFoods.SetFoods;

	/**
	 * 套餐表
	 */
	public static final com.breakfast.domain.tables.TSetMeal SetMeal = com.breakfast.domain.tables.TSetMeal.SetMeal;

	/**
	 * 分享信息表
	 */
	public static final com.breakfast.domain.tables.TShare Share = com.breakfast.domain.tables.TShare.Share;

	/**
	 * 人员表
	 */
	public static final com.breakfast.domain.tables.TUser User = com.breakfast.domain.tables.TUser.User;

	/**
	 * 快递员详情
	 */
	public static final com.breakfast.domain.tables.TUserCourier UserCourier = com.breakfast.domain.tables.TUserCourier.UserCourier;

	/**
	 * 用户详情
	 */
	public static final com.breakfast.domain.tables.TUserCustomer UserCustomer = com.breakfast.domain.tables.TUserCustomer.UserCustomer;

	/**
	 * 用户摄入元素统计表
	 */
	public static final com.breakfast.domain.tables.TUserElementStatistics UserElementStatistics = com.breakfast.domain.tables.TUserElementStatistics.UserElementStatistics;
}
